#!/usr/bin/env npx tsx

// teneo-skills-autogenerated/cli/daemon.ts
import "dotenv/config";
import * as http from "node:http";
import * as nodeFs from "node:fs";
import * as nodePath from "node:path";
import * as nodeOs from "node:os";
import { TeneoSDK, SDKConfigBuilder } from "@teneo-protocol/sdk";
import {
  createWalletClient,
  createPublicClient,
  http as viemHttp,
  defineChain
} from "viem";
import { privateKeyToAccount } from "viem/accounts";
import * as allChains from "viem/chains";
import * as nodeCrypto from "node:crypto";
var WS_URL = process.env.TENEO_WS_URL || "wss://backend.developer.chatroom.teneo-protocol.ai/ws";
var PRIVATE_KEY = process.env.TENEO_PRIVATE_KEY;
var DEFAULT_ROOM = process.env.TENEO_DEFAULT_ROOM || "";
var DEFAULT_CHAIN = process.env.TENEO_DEFAULT_CHAIN || "base";
var DAEMON_PORT = parseInt(process.env.TENEO_DAEMON_PORT || "19876");
var IDLE_TIMEOUT_MS = 10 * 60 * 1e3;
var currentTxSigningMode = "auto";
var connectingPromise = null;
var pendingTxQueue = /* @__PURE__ */ new Map();
var CHAIN_TO_CAIP2 = {
  base: "eip155:8453",
  peaq: "eip155:3338",
  avalanche: "eip155:43114",
  avax: "eip155:43114",
  xlayer: "eip155:196",
  "x-layer": "eip155:196"
};
var CHAIN_TO_USDC = {
  base: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
  peaq: "0xc2d830fdf0497e59d68f8a3e4c1213e86a39afdf",
  avalanche: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E",
  avax: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E",
  xlayer: "0x74b7F16337b8972027F6196A17a631aC6dE26d22",
  "x-layer": "0x74b7F16337b8972027F6196A17a631aC6dE26d22"
};
var PAYMENT_NETWORK_PRIORITY = ["base", "avalanche", "xlayer", "peaq"];
var BALANCE_CHECK_TIMEOUT_MS = 4e3;
var ERC20_BALANCE_ABI = [{ inputs: [{ name: "account", type: "address" }], name: "balanceOf", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" }];
async function fetchUsdcBalance(address, chainName) {
  const usdcAddr = CHAIN_TO_USDC[chainName];
  if (!usdcAddr) return { chain: chainName, balance: null, error: `Unknown chain: ${chainName}` };
  const caip2 = CHAIN_TO_CAIP2[chainName];
  if (!caip2) return { chain: chainName, balance: null, error: `No CAIP2 for chain: ${chainName}` };
  const chainId = parseInt(caip2.split(":")[1]);
  const chain = getChain(chainId);
  try {
    const client = createPublicClient({ chain, transport: viemHttp() });
    const balance = await Promise.race([
      client.readContract({
        address: usdcAddr,
        abi: ERC20_BALANCE_ABI,
        functionName: "balanceOf",
        args: [address]
      }),
      new Promise((_, reject) => setTimeout(() => reject(new Error("timeout")), BALANCE_CHECK_TIMEOUT_MS))
    ]);
    return { chain: chainName, balance: BigInt(balance), error: null };
  } catch (err) {
    return { chain: chainName, balance: null, error: err.message };
  }
}
async function findFundedNetworks(address, exclude = []) {
  const checks = PAYMENT_NETWORK_PRIORITY.filter((c) => !exclude.includes(c)).map((c) => fetchUsdcBalance(address, c));
  const results = await Promise.all(checks);
  return results.filter((r) => r.balance !== null && r.balance > 0n).map((r) => ({ chain: r.chain, balance: r.balance })).sort((a, b) => a.balance > b.balance ? -1 : 1);
}
function formatMicroUsdc(microUsdc) {
  const sign = microUsdc < 0n ? "-" : "";
  const abs = microUsdc < 0n ? -microUsdc : microUsdc;
  const whole = abs / 1000000n;
  const frac = (abs % 1000000n).toString().padStart(6, "0");
  return `${sign}${whole}.${frac}`;
}
var WALLET_DIR = nodePath.join(nodeOs.homedir(), ".teneo-wallet");
var WALLET_FILE = nodePath.join(WALLET_DIR, "wallet.json");
var SECRET_FILE = nodePath.join(WALLET_DIR, ".secret");
var PID_FILE = nodePath.join(WALLET_DIR, "daemon.pid");
var PORT_FILE = nodePath.join(WALLET_DIR, "daemon.port");
var CHAIN_BY_ID = {};
for (const key of Object.keys(allChains)) {
  const c = allChains[key];
  if (c && typeof c === "object" && "id" in c)
    CHAIN_BY_ID[c.id] = c;
}
function getChain(chainId) {
  if (CHAIN_BY_ID[chainId]) return CHAIN_BY_ID[chainId];
  return defineChain({
    id: chainId,
    name: `Chain ${chainId}`,
    nativeCurrency: { name: "ETH", symbol: "ETH", decimals: 18 },
    rpcUrls: { default: { http: [`https://rpc.chain${chainId}.org`] } }
  });
}
function ensureWalletDir() {
  if (!nodeFs.existsSync(WALLET_DIR))
    nodeFs.mkdirSync(WALLET_DIR, { recursive: true, mode: 448 });
}
function getOrCreateMasterSecret() {
  ensureWalletDir();
  if (nodeFs.existsSync(SECRET_FILE)) {
    return Buffer.from(nodeFs.readFileSync(SECRET_FILE, "utf8").trim(), "hex");
  }
  const secret = nodeCrypto.randomBytes(32);
  nodeFs.writeFileSync(SECRET_FILE, secret.toString("hex"), { mode: 384 });
  nodeFs.chmodSync(SECRET_FILE, 384);
  return secret;
}
function decryptPK(encryptedKey, iv, authTag, masterSecret) {
  const decipher = nodeCrypto.createDecipheriv("aes-256-gcm", masterSecret, Buffer.from(iv, "base64"));
  decipher.setAuthTag(Buffer.from(authTag, "base64"));
  return Buffer.concat([decipher.update(Buffer.from(encryptedKey, "base64")), decipher.final()]).toString("utf8");
}
function encryptPK(pk, masterSecret) {
  const iv = nodeCrypto.randomBytes(12);
  const cipher = nodeCrypto.createCipheriv("aes-256-gcm", masterSecret, iv);
  const encrypted = Buffer.concat([cipher.update(pk, "utf8"), cipher.final()]);
  return { encryptedKey: encrypted.toString("base64"), iv: iv.toString("base64"), authTag: cipher.getAuthTag().toString("base64") };
}
function loadWallet() {
  if (!nodeFs.existsSync(WALLET_FILE)) return null;
  try {
    return JSON.parse(nodeFs.readFileSync(WALLET_FILE, "utf8"));
  } catch {
    return null;
  }
}
function saveWallet(data) {
  ensureWalletDir();
  nodeFs.writeFileSync(WALLET_FILE, JSON.stringify(data, null, 2), { mode: 384 });
  nodeFs.chmodSync(WALLET_FILE, 384);
}
function requireKey() {
  if (PRIVATE_KEY) return PRIVATE_KEY;
  const wallet = loadWallet();
  if (wallet) {
    const secret2 = getOrCreateMasterSecret();
    return decryptPK(wallet.encryptedKey, wallet.iv, wallet.authTag, secret2);
  }
  log("No wallet found \u2014 generating a new one automatically...");
  const privateKey = nodeCrypto.randomBytes(32).toString("hex");
  const account = privateKeyToAccount(`0x${privateKey}`);
  const secret = getOrCreateMasterSecret();
  const encrypted = encryptPK(privateKey, secret);
  saveWallet({
    address: account.address,
    encryptedKey: encrypted.encryptedKey,
    iv: encrypted.iv,
    authTag: encrypted.authTag,
    createdAt: (/* @__PURE__ */ new Date()).toISOString()
  });
  log(`Wallet created: ${account.address}`);
  log("Fund this address with USDC on Base, Avalanche, Peaq, or X Layer to use paid agents.");
  return privateKey;
}
var sdk = null;
var lastActivity = Date.now();
var startTime = Date.now();
function log(msg) {
  const ts = (/* @__PURE__ */ new Date()).toISOString();
  console.error(`[daemon ${ts}] ${msg}`);
}
function buildSDK(key) {
  const normalizedKey = key.startsWith("0x") ? key : `0x${key}`;
  const builder = new SDKConfigBuilder().withWebSocketUrl(WS_URL).withAuthentication(normalizedKey).withReconnection({ enabled: true, delay: 3e3, maxAttempts: 5 }).withCache(true, 6e5, 500).withPayments({
    autoApprove: true,
    quoteTimeout: 12e4,
    network: CHAIN_TO_CAIP2[DEFAULT_CHAIN] || "eip155:8453",
    asset: CHAIN_TO_USDC[DEFAULT_CHAIN] || "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
  });
  const config = builder.build();
  config.messageTimeout = 12e4;
  config.responseFormat = "both";
  return new TeneoSDK(config);
}
var CHAIN_NAMES = {
  1: "ethereum",
  42161: "arbitrum",
  137: "polygon",
  8453: "base",
  59144: "linea",
  43114: "avalanche",
  3338: "peaq",
  196: "x-layer",
  84532: "base-sepolia"
};
function formatTxHashWithChain(txHash, chainId) {
  const name = CHAIN_NAMES[chainId];
  return name ? `${txHash}|${name}` : txHash;
}
async function waitForTxReceipt(chainId, txHash) {
  const chain = getChain(chainId);
  const client = createPublicClient({ chain, transport: viemHttp() });
  const receipt = await client.waitForTransactionReceipt({ hash: txHash });
  return { reverted: receipt.status === "reverted" };
}
async function signBroadcastAndConfirm(sdkInstance, account, taskId, tx, room) {
  const chain = getChain(tx.chainId);
  const walletClient = createWalletClient({ account, chain, transport: viemHttp() });
  const txHash = await walletClient.sendTransaction({
    to: tx.to,
    value: tx.value ? BigInt(tx.value) : 0n,
    data: tx.data || void 0,
    chain
  });
  log(`TX broadcast: ${txHash}`);
  await sdkInstance.sendTxResult(taskId, "broadcasted", formatTxHashWithChain(txHash, tx.chainId), void 0, room, tx.chainId);
  log("Waiting for on-chain confirmation...");
  const receipt = await waitForTxReceipt(tx.chainId, txHash);
  const formattedHash = formatTxHashWithChain(txHash, tx.chainId);
  if (receipt.reverted) {
    log(`TX reverted on-chain: ${txHash}`);
    await sdkInstance.sendTxResult(taskId, "failed", formattedHash, "Transaction reverted on-chain", room, tx.chainId);
    return { txHash, status: "failed", error: "Transaction reverted on-chain" };
  }
  log(`TX confirmed: ${txHash}`);
  await sdkInstance.sendTxResult(taskId, "confirmed", formattedHash, void 0, room, tx.chainId);
  return { txHash, status: "confirmed" };
}
function registerTxSigner(sdkInstance) {
  const key = requireKey();
  const account = privateKeyToAccount(key.startsWith("0x") ? key : `0x${key}`);
  sdkInstance.on("wallet:tx_requested", async (data) => {
    const { taskId, tx, agentName, description, room } = data;
    const isOptional = data.optional === true;
    log(`TX requested by ${agentName || "agent"}: ${description || "on-chain transaction"}`);
    if (currentTxSigningMode === "manual") {
      log(`TX queued for manual approval (taskId: ${taskId})`);
      pendingTxQueue.set(taskId, {
        taskId,
        tx,
        description: description || "Transaction requested by agent",
        agentName: agentName || "agent",
        optional: isOptional,
        room,
        receivedAt: (/* @__PURE__ */ new Date()).toISOString()
      });
      return;
    }
    try {
      await signBroadcastAndConfirm(sdkInstance, account, taskId, tx, room);
    } catch (err) {
      log(`TX failed: ${err.message}`);
      await sdkInstance.sendTxResult(taskId, "failed", void 0, err.message, room, tx.chainId);
    }
  });
}
async function ensureConnected() {
  if (sdk) {
    try {
      const h = sdk.getHealth();
      if (h && h.status !== "disconnected") return sdk;
    } catch {
    }
    try {
      sdk.disconnect();
    } catch {
    }
    sdk = null;
  }
  const key = requireKey();
  const maxRetries = 5;
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      sdk = buildSDK(key);
      await sdk.connect();
      registerTxSigner(sdk);
      log("SDK connected");
      return sdk;
    } catch (err) {
      sdk = null;
      if (attempt < maxRetries) {
        const delay = Math.min(attempt * 2e3, 1e4);
        log(`Connection failed (attempt ${attempt}/${maxRetries}): ${err.message}. Retrying in ${delay / 1e3}s...`);
        await sleep(delay);
      } else {
        throw new Error(`Failed to connect to Teneo network after ${maxRetries} attempts: ${err.message}`);
      }
    }
  }
  throw new Error("Failed to connect to Teneo network");
}
function liveRooms(s) {
  return [...s.getRooms()];
}
async function refreshRooms(s) {
  return s.listRooms();
}
var LEGACY_DEFAULT_CATALOG_PRICE_USDC = 1e-3;
function parseCommands(agent) {
  if (!agent.commands) return [];
  if (Array.isArray(agent.commands)) return agent.commands;
  try {
    return JSON.parse(agent.commands);
  } catch {
    return [];
  }
}
function parseCatalogPricePerUnit(raw) {
  if (typeof raw === "number" && Number.isFinite(raw)) return raw;
  if (typeof raw === "string" && raw.trim() !== "") {
    const parsed = Number(raw);
    if (Number.isFinite(parsed)) return parsed;
  }
  return void 0;
}
function hasExplicitCatalogPrice(pricePerUnit) {
  return typeof pricePerUnit === "number" && Number.isFinite(pricePerUnit);
}
function getCatalogBasePrice(pricePerUnit) {
  return hasExplicitCatalogPrice(pricePerUnit) ? pricePerUnit : LEGACY_DEFAULT_CATALOG_PRICE_USDC;
}
function normalizeAgent(a) {
  const id = a.id || a.agent_id;
  const name = a.name || a.agent_name;
  const cmds = parseCommands(a);
  return {
    agent_id: id,
    agent_name: name,
    description: a.description || "",
    status: a.status,
    is_online: a.status === "online" || a.is_online,
    type: a.type || a.agent_type || "command",
    commands: cmds.map((c) => {
      const parsed = parseCatalogPricePerUnit(c.pricePerUnit ?? c.price_per_unit);
      const basePrice = getCatalogBasePrice(parsed);
      const isExplicitlyFree = hasExplicitCatalogPrice(parsed) && parsed === 0;
      return {
        trigger: c.trigger,
        description: c.description,
        usage: `@${id} ${c.trigger}${c.argument ? " " + c.argument : ""}`,
        price: basePrice,
        price_scope: !hasExplicitCatalogPrice(parsed) ? "legacy-default-base-price" : parsed > 0 ? "base-command-price-only" : "free",
        task_unit: c.taskUnit || "per-query",
        is_free: isExplicitlyFree,
        pricing_note: !hasExplicitCatalogPrice(parsed) ? `Catalog price missing. Legacy default ${LEGACY_DEFAULT_CATALOG_PRICE_USDC} USDC applied. Exact total comes from the live task_quote.` : parsed > 0 ? "Base catalog price only. Exact signed total comes from the live task_quote." : "FREE",
        parameters: c.parameters || [],
        argument: c.argument,
        pricePerUnit: parsed,
        taskUnit: c.taskUnit
      };
    })
  };
}
async function fetchAgentsViaSDK(s) {
  const rooms = await liveRooms(s);
  if (rooms.length === 0) return [];
  const room = rooms[0];
  const roomAgents = await s.listRoomAgents(room.id);
  const available = [];
  let offset = 0;
  const limit = 50;
  let result;
  do {
    result = await s.listAvailableAgents(room.id, { limit, offset });
    available.push(...result.agents);
    offset += limit;
  } while (result.hasMore);
  return [...roomAgents, ...available];
}
async function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}
async function getAgentDetailsLive(s, agentId, timeoutMs = 1e4) {
  try {
    const wsClient = s.wsClient;
    if (!wsClient?.isConnected) return null;
    return await new Promise((resolve) => {
      const timeout = setTimeout(() => {
        wsClient.off("message:received", handler);
        resolve(null);
      }, timeoutMs);
      const handler = (msg) => {
        if (msg.type === "agent_details_response" && msg.data?.agent) {
          const agent = msg.data.agent;
          if (agent.agent_id === agentId) {
            clearTimeout(timeout);
            wsClient.off("message:received", handler);
            resolve(agent);
          }
        }
      };
      wsClient.on("message:received", handler);
      wsClient.sendMessage({ type: "get_agent_details", data: { agent_id: agentId } });
    });
  } catch {
    return null;
  }
}
async function enrichAgentsWithDetails(s, agents) {
  const wsClient = s.wsClient;
  if (!wsClient?.isConnected || agents.length === 0) return agents;
  const pending = /* @__PURE__ */ new Map();
  const results = /* @__PURE__ */ new Map();
  for (const agent of agents) {
    pending.set(agent.agent_id, agent);
  }
  return new Promise((resolve) => {
    const totalTimeout = Math.min(agents.length * 200 + 1e4, 6e4);
    const timer = setTimeout(() => {
      wsClient.off("message:received", handler);
      finalize();
    }, totalTimeout);
    const handler = (msg) => {
      if (msg.type === "agent_details_response" && msg.data?.agent) {
        const agent = msg.data.agent;
        if (pending.has(agent.agent_id)) {
          results.set(agent.agent_id, { ...normalizeAgent(agent), _source: "live" });
          pending.delete(agent.agent_id);
          if (pending.size === 0) {
            clearTimeout(timer);
            wsClient.off("message:received", handler);
            finalize();
          }
        }
      }
    };
    function finalize() {
      const merged = agents.map(
        (a) => results.get(a.agent_id) || { ...a, _source: "cached" }
      );
      resolve(merged);
    }
    wsClient.on("message:received", handler);
    (async () => {
      for (const agent of agents) {
        wsClient.sendMessage({ type: "get_agent_details", data: { agent_id: agent.agent_id } }).catch(() => {
        });
        await sleep(200);
      }
    })();
  });
}
var handlers = {
  // Discovery (via SDK WebSocket — no REST)
  "discover": async (s) => {
    const rawAgents = await fetchAgentsViaSDK(s);
    const normalized = rawAgents.map(normalizeAgent);
    const enriched = await enrichAgentsWithDetails(s, normalized);
    const onlineAgents = enriched.filter((a) => a.is_online);
    const commandIndex = [];
    for (const agent of onlineAgents) {
      for (const cmd of agent.commands) {
        commandIndex.push({
          usage: cmd.usage,
          agent_id: agent.agent_id,
          agent_name: agent.agent_name,
          trigger: cmd.trigger,
          description: cmd.description,
          price: cmd.price,
          is_free: cmd.is_free,
          task_unit: cmd.task_unit,
          parameters: cmd.parameters
        });
      }
    }
    return {
      _meta: {
        generated_at: (/* @__PURE__ */ new Date()).toISOString(),
        websocket: WS_URL,
        total_agents: enriched.length,
        online_agents: onlineAgents.length,
        total_commands: commandIndex.length
      },
      fee_config: {
        model: "percentage",
        percentage: "1%",
        percentageRaw: 0.01,
        minimumFeeUSD: "0.001",
        minimumFeeRaw: 1e-3,
        status: "embedded",
        coordinatorFeeUsdc: 5e-4
      },
      payment_networks: Object.entries(CHAIN_TO_CAIP2).reduce((acc, [name, caip2]) => {
        if (!acc[name]) acc[name] = { caip2, usdc: CHAIN_TO_USDC[name] || null };
        return acc;
      }, {}),
      pricing_semantics: {
        catalogCommandPriceField: "agents[].commands[].price",
        catalogCommandPriceMeaning: "base-command-price-only",
        runtimePriceField: "task_quote.pricing.price_per_unit",
        runtimeFeeField: "task_quote.facilitator_fee",
        runtimeFeeUnit: "micro-usdc",
        note: "Do not estimate the final signed x402 total from fee_config alone; inspect the live task_quote."
      },
      agents: enriched,
      online_agents: onlineAgents,
      command_index: commandIndex
    };
  },
  "list-agents": async (s, args) => {
    let agents = (await fetchAgentsViaSDK(s)).map(normalizeAgent);
    if (args?.search) {
      const term = args.search.toLowerCase();
      agents = agents.filter((a) => a.agent_id.toLowerCase().includes(term) || a.agent_name.toLowerCase().includes(term) || a.description.toLowerCase().includes(term));
    }
    if (args?.online) agents = agents.filter((a) => a.is_online);
    if (args?.free) agents = agents.filter((a) => a.commands.some((c) => c.is_free));
    const enriched = await enrichAgentsWithDetails(s, agents);
    return { count: enriched.length, agents: enriched };
  },
  "info": async (s, { agentId }) => {
    const details = await getAgentDetailsLive(s, agentId);
    if (details) {
      return { ...normalizeAgent(details), _source: "live" };
    }
    const rawAgents = await fetchAgentsViaSDK(s);
    const all = rawAgents.map(normalizeAgent);
    const term = agentId.toLowerCase();
    const agent = all.find((a) => a.agent_id === agentId) || all.find((a) => a.agent_id.toLowerCase() === term) || all.find((a) => a.agent_id.toLowerCase().includes(term) || a.agent_name.toLowerCase().includes(term) || a.description.toLowerCase().includes(term));
    if (!agent) {
      const similar = all.filter((a) => a.agent_id.toLowerCase().includes(term) || a.agent_name.toLowerCase().includes(term) || a.description.toLowerCase().includes(term)).slice(0, 5);
      return { error: "not_found", agent_id: agentId, suggestions: similar.map((a) => a.agent_id) };
    }
    const [enriched] = await enrichAgentsWithDetails(s, [agent]);
    return enriched;
  },
  // Health
  "health": async (s) => s.getHealth(),
  // Room management
  "rooms": async (s) => {
    const rooms = await liveRooms(s);
    return { count: rooms.length, rooms: rooms.map((r) => ({ id: r.id, name: r.name, is_public: r.is_public, is_owner: r.is_owner, description: r.description })) };
  },
  "room-agents": async (s, { roomId }) => {
    const agents = await s.listRoomAgents(roomId);
    return { roomId, count: agents.length, agents: agents.map((a) => ({ id: a.agent_id, name: a.agent_name, status: a.status })) };
  },
  "create-room": async (s, { name, description, isPublic }) => {
    const r = await s.createRoom({ name, description, isPublic });
    await refreshRooms(s);
    return { status: "created", room: { id: r.id, name: r.name, is_public: r.is_public } };
  },
  "update-room": async (s, { roomId, name, description }) => {
    const updates = {};
    if (name) updates.name = name;
    if (description) updates.description = description;
    const result = await s.updateRoom(roomId, updates);
    await refreshRooms(s);
    return { status: "updated", room: result };
  },
  "delete-room": async (s, { roomId }) => {
    await s.deleteRoom(roomId);
    await refreshRooms(s);
    return { status: "deleted", roomId };
  },
  "add-agent": async (s, { roomId, agentId }) => {
    await s.addAgentToRoom(roomId, agentId);
    return { status: "added", roomId, agentId };
  },
  "remove-agent": async (s, { roomId, agentId }) => {
    await s.removeAgentFromRoom(roomId, agentId);
    return { status: "removed", roomId, agentId };
  },
  "owned-rooms": async (s) => {
    const rooms = (await liveRooms(s)).filter((r) => r.is_owner);
    return { count: rooms.length, rooms: rooms.map((r) => ({ id: r.id, name: r.name, is_public: r.is_public })) };
  },
  "shared-rooms": async (s) => {
    const rooms = (await liveRooms(s)).filter((r) => !r.is_owner);
    return { count: rooms.length, rooms: rooms.map((r) => ({ id: r.id, name: r.name, is_public: r.is_public })) };
  },
  "subscribe": async (s, { roomId }) => {
    await s.subscribeToPublicRoom(roomId);
    return { status: "subscribed", roomId };
  },
  "unsubscribe": async (s, { roomId }) => {
    await s.unsubscribeFromPublicRoom(roomId);
    return { status: "unsubscribed", roomId };
  },
  // Agent commands (with autosummon — uses sendMessage like the orchestrator)
  // Supports multi-step TX flows: agent sends approval TX, we sign it, agent sends swap TX, we sign it, agent sends final result.
  "command": async (s, { agent, cmd, room, chain, timeout, autoSignTx }) => {
    currentTxSigningMode = autoSignTx === false ? "manual" : "auto";
    try {
      const roomAgents = await s.listRoomAgents(room);
      const agentInRoom = roomAgents.some((a) => a.agent_id === agent);
      if (!agentInRoom) {
        const allRooms = liveRooms(s);
        let bestRoom = null;
        for (const r of allRooms) {
          if (r.id === room) continue;
          try {
            const agents = await s.listRoomAgents(r.id);
            if (agents.some((a) => a.agent_id === agent)) {
              bestRoom = r.id;
              log(`Autosummon: found agent "${agent}" already in room "${r.id}"`);
              break;
            }
          } catch {
          }
        }
        if (bestRoom) {
          room = bestRoom;
        } else {
          if (roomAgents.length >= 5) {
            const toRemove = roomAgents.find((a) => a.agent_id !== agent) || roomAgents[0];
            log(`Autosummon: room full, removing "${toRemove.agent_id || toRemove.id}" to make space`);
            await s.removeAgentFromRoom(room, toRemove.agent_id || toRemove.id);
            await sleep(1e3);
          }
          log(`Autosummon: agent "${agent}" not in room, adding...`);
          await s.addAgentToRoom(room, agent);
          await sleep(1e3);
          log(`Autosummon: agent "${agent}" added to room "${room}"`);
        }
      }
    } catch (checkErr) {
      log(`Autosummon check failed (non-fatal): ${checkErr.message}`);
    }
    const effectiveTimeout = timeout || 12e4;
    const commandText = `@${agent} ${cmd}`;
    const explicitChain = chain || null;
    const attemptedNetworks = [];
    let preflightChain = null;
    if (!explicitChain) {
      try {
        const key = requireKey();
        const acct = privateKeyToAccount(key.startsWith("0x") ? key : `0x${key}`);
        const funded = await findFundedNetworks(acct.address);
        if (funded.length > 0) {
          preflightChain = funded[0].chain;
          log(`Preflight: best funded network is ${preflightChain} (${formatMicroUsdc(funded[0].balance)} USDC)`);
        }
      } catch (err) {
        log(`Preflight balance check failed (non-fatal): ${err.message}`);
      }
    }
    const buildMessageOptions = (networkOverride) => {
      const resolvedNetwork = networkOverride ? CHAIN_TO_CAIP2[networkOverride] || networkOverride : explicitChain ? CHAIN_TO_CAIP2[explicitChain] || explicitChain : preflightChain ? CHAIN_TO_CAIP2[preflightChain] || preflightChain : void 0;
      if (resolvedNetwork && !attemptedNetworks.includes(resolvedNetwork)) attemptedNetworks.push(resolvedNetwork);
      return {
        room,
        waitForResponse: true,
        timeout: effectiveTimeout,
        format: "both",
        ...resolvedNetwork ? { network: resolvedNetwork } : {}
      };
    };
    const messageOptions = buildMessageOptions();
    const cmdLower = cmd.toLowerCase();
    const isMultiStepTx = cmdLower.startsWith("swap") || cmdLower.startsWith("bridge") || cmdLower.startsWith("transfer");
    const wsClient = s.wsClient;
    if (isMultiStepTx) {
      log(`Multi-step TX flow detected for "${cmd}"`);
      const messages = [];
      let txCount = 0;
      const result = await new Promise((resolve, reject) => {
        let lastTxTime = 0;
        const txWaitGrace = 3e4;
        let idleTimer;
        const resetIdleTimer = (label) => {
          clearTimeout(idleTimer);
          idleTimer = setTimeout(() => {
            log(`Idle timeout reached after last activity: ${label}`);
            cleanup2();
            if (messages.length > 0) {
              resolve({ steps: messages, txCount, status: "timeout", note: "Flow idle-timed out but some steps completed" });
            } else {
              reject(new Error("Multi-step TX flow timed out with no responses"));
            }
          }, txWaitGrace);
        };
        const flowTimeout = setTimeout(() => {
          clearTimeout(idleTimer);
          cleanup2();
          if (messages.length > 0) {
            resolve({ steps: messages, txCount, status: "timeout", note: "Flow timed out but some steps completed" });
          } else {
            reject(new Error("Multi-step TX flow timed out with no responses"));
          }
        }, effectiveTimeout);
        resetIdleTimer("flow start");
        const isRelevantError = (msg) => msg.includes("Payment verification failed") || msg.includes("payment") || msg.includes("Agent not found") || msg.includes("not found") || msg.includes("insufficient");
        const isFlowComplete = (content) => {
          const lower = content.toLowerCase();
          return lower.includes("swap completed") || lower.includes("swap successful") || lower.includes("swap failed") || lower.includes("bridge completed") || lower.includes("transfer completed");
        };
        const isIntermediateMessage = (content) => {
          const lower = content.toLowerCase();
          return lower.includes("transaction confirmed") || lower.includes("approval confirmed") || lower.includes("approved") || lower.includes("preparing swap") || lower.includes("proceeding") || lower.includes("next step");
        };
        const txHandler = (data) => {
          txCount++;
          lastTxTime = Date.now();
          log(`Multi-step TX #${txCount} requested by ${data.agentName || agent}`);
          messages.push({ type: "tx_requested", txCount, description: data.description, timestamp: (/* @__PURE__ */ new Date()).toISOString() });
          resetIdleTimer(`TX #${txCount} requested`);
        };
        const txResultHandler = (data) => {
          log(`TX result: ${data.status} ${data.txHash || ""}`);
          messages.push({ type: "tx_result", status: data.status, txHash: data.txHash, timestamp: (/* @__PURE__ */ new Date()).toISOString() });
          resetIdleTimer(`TX result: ${data.status}`);
        };
        const msgHandler = (msg) => {
          if (msg.type === "agent_selected") {
            const selectedId = msg.data?.agent_id || msg.content?.agent_id || "";
            if (selectedId && selectedId.toLowerCase() !== agent.toLowerCase()) {
              log(`Direct-agent mismatch: expected "${agent}", got "${selectedId}"`);
              clearTimeout(flowTimeout);
              cleanup2();
              reject(new Error(`Direct-agent mismatch: expected "${agent}", coordinator selected "${selectedId}"`));
              return;
            }
          }
          if (msg.type === "message" && (msg.from === agent || msg.data?.agent_id === agent)) {
            const content = msg.content || msg.humanized || "";
            log(`Multi-step msg from ${agent}: ${content.substring(0, 100)}...`);
            messages.push({
              type: "agent_message",
              humanized: msg.humanized || content,
              raw: msg,
              content,
              timestamp: (/* @__PURE__ */ new Date()).toISOString()
            });
            if (isFlowComplete(content)) {
              log(`Flow complete: "${content.substring(0, 80)}". Resolving in 5s...`);
              clearTimeout(idleTimer);
              setTimeout(() => {
                clearTimeout(flowTimeout);
                cleanup2();
                resolve({ steps: messages, txCount, status: "completed" });
              }, 5e3);
            } else if (isIntermediateMessage(content)) {
              log(`Intermediate step (TX #${txCount}): "${content.substring(0, 80)}". Waiting up to ${txWaitGrace / 1e3}s for next step...`);
              lastTxTime = Date.now();
              resetIdleTimer(`intermediate: ${content.substring(0, 40)}`);
            } else if (content.toLowerCase().includes("error")) {
              log(`Error detected: "${content.substring(0, 80)}". Resolving in 5s...`);
              clearTimeout(idleTimer);
              setTimeout(() => {
                clearTimeout(flowTimeout);
                cleanup2();
                resolve({ steps: messages, txCount, status: "error" });
              }, 5e3);
            } else {
              resetIdleTimer(`agent message`);
            }
          }
          if (msg.type === "error" && msg.data) {
            const errMsg = msg.data.message || msg.content || "";
            const errCode = msg.data.code || 0;
            if (isRelevantError(errMsg) || errCode === 402) {
              clearTimeout(flowTimeout);
              cleanup2();
              reject(new Error(`Agent error (${errCode}): ${errMsg}`));
            }
          }
        };
        const sdkErrorHandler = (err) => {
          if (isRelevantError(err.message)) {
            clearTimeout(flowTimeout);
            cleanup2();
            reject(new Error(`Agent error: ${err.message}`));
          }
        };
        const cleanup2 = () => {
          clearTimeout(idleTimer);
          s.off("error", sdkErrorHandler);
          s.off("wallet:tx_requested", txHandler);
          s.off("wallet:tx_completed", txResultHandler);
          if (wsClient) {
            wsClient.off("message:received", msgHandler);
          }
        };
        s.on("error", sdkErrorHandler);
        s.on("wallet:tx_requested", txHandler);
        s.on("wallet:tx_completed", txResultHandler);
        if (wsClient) {
          wsClient.on("message:received", msgHandler);
        }
        s.sendMessage(commandText, { ...messageOptions, waitForResponse: false }).catch((err) => {
          clearTimeout(flowTimeout);
          cleanup2();
          reject(err);
        });
      });
      return result;
    }
    try {
      const response = await new Promise((resolve, reject) => {
        let settled = false;
        const settle = (fn, val) => {
          if (settled) return;
          settled = true;
          cleanup2();
          fn(val);
        };
        const isRelevantError = (msg) => msg.includes("Payment verification failed") || msg.includes("payment") || msg.includes("Agent not found") || msg.includes("not found") || msg.includes("insufficient");
        const sdkErrorHandler = (err) => {
          if (isRelevantError(err.message)) {
            settle(reject, new Error(`Agent error: ${err.message}`));
          }
        };
        const wsMessageHandler = (msg) => {
          if (msg.type === "agent_selected") {
            const selectedId = msg.data?.agent_id || msg.content?.agent_id || "";
            if (selectedId && selectedId.toLowerCase() !== agent.toLowerCase()) {
              settle(reject, new Error(`Direct-agent mismatch: expected "${agent}", coordinator selected "${selectedId}"`));
              return;
            }
          }
          if (msg.type === "error" && msg.data) {
            const errMsg = msg.data.message || msg.content || "";
            const errCode = msg.data.code || 0;
            if (isRelevantError(errMsg) || errCode === 402) {
              settle(reject, new Error(`Agent error (${errCode}): ${errMsg}`));
            }
          }
        };
        const cleanup2 = () => {
          s.off("error", sdkErrorHandler);
          if (wsClient) wsClient.off("message:received", wsMessageHandler);
        };
        s.on("error", sdkErrorHandler);
        if (wsClient) wsClient.on("message:received", wsMessageHandler);
        s.sendMessage(commandText, messageOptions).then((res) => settle(resolve, res)).catch((err) => settle(reject, err));
      });
      if (response && (response.humanized || response.raw || response.content)) {
        return {
          humanized: response.humanized,
          raw: response.raw,
          content: response.content,
          metadata: response.metadata
        };
      }
      return { status: "sent", note: "Command sent. Response may arrive asynchronously." };
    } catch (cmdError) {
      const is402 = cmdError.message?.includes("402") || cmdError.message?.includes("Payment verification failed") || cmdError.message?.includes("insufficient");
      if (is402 && !explicitChain) {
        const key = requireKey();
        const account = privateKeyToAccount(key.startsWith("0x") ? key : `0x${key}`);
        const funded = await findFundedNetworks(account.address, attemptedNetworks.map((caip2) => {
          for (const [name, c] of Object.entries(CHAIN_TO_CAIP2)) {
            if (c === caip2) return name;
          }
          return caip2;
        }));
        if (funded.length > 0) {
          const nextChain = funded[0].chain;
          log(`Payment failed, retrying on ${nextChain} (balance: ${formatMicroUsdc(funded[0].balance)} USDC)`);
          const retryOptions = buildMessageOptions(nextChain);
          const retryResponse = await s.sendMessage(commandText, retryOptions);
          if (retryResponse && (retryResponse.humanized || retryResponse.raw || retryResponse.content)) {
            return {
              humanized: retryResponse.humanized,
              raw: retryResponse.raw,
              content: retryResponse.content,
              metadata: retryResponse.metadata,
              _payment_retry: { original_error: cmdError.message, retried_on: nextChain }
            };
          }
          return { status: "sent", _payment_retry: { retried_on: nextChain } };
        }
      }
      throw cmdError;
    }
  },
  // Internal — not exposed as CLI commands, but available via daemon HTTP API
  "quote": async (s, { message, room, chain }) => {
    const resolvedChain = CHAIN_TO_CAIP2[chain || DEFAULT_CHAIN] || chain || CHAIN_TO_CAIP2[DEFAULT_CHAIN];
    const q = await s.requestQuote(message, room, resolvedChain);
    return { taskId: q.taskId, agentId: q.agentId, agentName: q.agentName, command: q.command, pricing: q.pricing, expiresAt: q.expiresAt };
  },
  // TX approval flow (for --no-auto-sign-tx mode)
  "pending-txs": async () => {
    const txs = Array.from(pendingTxQueue.values()).map((tx) => ({
      taskId: tx.taskId,
      description: tx.description,
      agentName: tx.agentName,
      to: tx.tx.to,
      value: tx.tx.value || "0",
      chainId: tx.tx.chainId,
      data: tx.tx.data ? tx.tx.data.slice(0, 42) + "..." : "none",
      optional: tx.optional,
      receivedAt: tx.receivedAt
    }));
    return { count: txs.length, transactions: txs };
  },
  "approve-tx": async (s, { taskId }) => {
    const pending = pendingTxQueue.get(taskId);
    if (!pending) return { error: "not_found", taskId, message: "No pending transaction with this taskId. Run pending-txs to see queued transactions." };
    pendingTxQueue.delete(taskId);
    const key = requireKey();
    const account = privateKeyToAccount(key.startsWith("0x") ? key : `0x${key}`);
    try {
      const result = await signBroadcastAndConfirm(s, account, pending.taskId, pending.tx, pending.room);
      return { status: "approved", ...result };
    } catch (err) {
      log(`Approve-tx failed: ${err.message}`);
      await s.sendTxResult(pending.taskId, "failed", void 0, err.message, pending.room, pending.tx.chainId);
      return { status: "failed", taskId, error: err.message };
    }
  },
  "reject-tx": async (s, { taskId }) => {
    const pending = pendingTxQueue.get(taskId);
    if (!pending) return { error: "not_found", taskId, message: "No pending transaction with this taskId. Run pending-txs to see queued transactions." };
    pendingTxQueue.delete(taskId);
    await s.sendTxResult(pending.taskId, "rejected", void 0, "User rejected transaction", pending.room, pending.tx.chainId);
    return { status: "rejected", taskId };
  },
  // Payment utilities
  "check-balance": async (s, { chain }) => {
    const key = requireKey();
    const account = privateKeyToAccount(key.startsWith("0x") ? key : `0x${key}`);
    const address = account.address;
    if (chain) {
      const result = await fetchUsdcBalance(address, chain);
      return {
        address,
        chain,
        usdc: result.balance !== null ? formatMicroUsdc(result.balance) : null,
        usdc_micro: result.balance?.toString() || null,
        error: result.error
      };
    }
    const funded = await findFundedNetworks(address);
    const allResults = await Promise.all(
      PAYMENT_NETWORK_PRIORITY.map((c) => fetchUsdcBalance(address, c))
    );
    return {
      address,
      balances: Object.fromEntries(allResults.map((r) => [r.chain, {
        usdc: r.balance !== null ? formatMicroUsdc(r.balance) : null,
        usdc_micro: r.balance?.toString() || null,
        error: r.error
      }])),
      funded_networks: funded.map((f) => f.chain),
      recommended_network: funded.length > 0 ? funded[0].chain : null
    };
  },
  "room-available-agents": async (s, { roomId }) => {
    const agents = await s.listAvailableAgents(roomId);
    return { roomId, count: agents.length, agents: agents.map((a) => ({ id: a.agent_id || a.id, name: a.agent_name || a.name, status: a.is_online ? "online" : "offline" })) };
  }
};
function readBody(req) {
  return new Promise((resolve, reject) => {
    let body = "";
    req.on("data", (chunk) => {
      body += chunk;
    });
    req.on("end", () => resolve(body));
    req.on("error", reject);
  });
}
var server = http.createServer(async (req, res) => {
  lastActivity = Date.now();
  res.setHeader("Content-Type", "application/json");
  try {
    if (req.method === "GET" && req.url === "/health") {
      if (connectingPromise) {
        await Promise.race([connectingPromise, sleep(15e3)]);
      }
      let sdkHealth = null;
      try {
        sdkHealth = sdk ? sdk.getHealth() : null;
      } catch {
      }
      const authenticated = sdkHealth?.connection?.authenticated || false;
      res.end(JSON.stringify({
        status: "ok",
        connected: !!sdk,
        authenticated,
        uptime: Math.floor((Date.now() - startTime) / 1e3),
        pid: process.pid,
        sdk_health: sdkHealth
      }));
      return;
    }
    if (req.method === "POST" && req.url === "/stop") {
      res.end(JSON.stringify({ status: "stopped" }));
      cleanup();
      setTimeout(() => process.exit(0), 100);
      return;
    }
    if (req.method === "POST" && req.url === "/exec") {
      const body = JSON.parse(await readBody(req));
      const { command, args } = body;
      const handler = handlers[command];
      if (!handler) {
        res.statusCode = 400;
        res.end(JSON.stringify({ error: `Unknown command: ${command}` }));
        return;
      }
      try {
        let s = await ensureConnected();
        let result;
        try {
          result = await handler(s, args || {});
        } catch (handlerErr) {
          const msg = handlerErr?.message || "";
          const code = handlerErr?.code;
          if (msg.includes("Not connected to Teneo network") || code === "NOT_CONNECTED") {
            log(`Connection lost during "${command}", reconnecting...`);
            sdk = null;
            s = await ensureConnected();
            result = await handler(s, args || {});
          } else {
            throw handlerErr;
          }
        }
        res.end(JSON.stringify({ result }));
      } catch (cmdErr) {
        log(`Command "${command}" failed: ${cmdErr.message}`);
        res.statusCode = 500;
        res.end(JSON.stringify({ error: cmdErr.message || String(cmdErr) }));
      }
      return;
    }
    res.statusCode = 404;
    res.end(JSON.stringify({ error: "Not found" }));
  } catch (err) {
    res.statusCode = 500;
    res.end(JSON.stringify({ error: err.message || String(err) }));
  }
});
function cleanup() {
  try {
    nodeFs.unlinkSync(PID_FILE);
  } catch {
  }
  try {
    nodeFs.unlinkSync(PORT_FILE);
  } catch {
  }
  if (sdk) try {
    sdk.disconnect();
  } catch {
  }
}
setInterval(() => {
  if (Date.now() - lastActivity > IDLE_TIMEOUT_MS) {
    log("Idle timeout reached, shutting down");
    cleanup();
    process.exit(0);
  }
}, 6e4);
process.on("uncaughtException", (err) => {
  log(`Uncaught exception: ${err.message}`);
});
process.on("unhandledRejection", (err) => {
  log(`Unhandled rejection: ${err?.message || err}`);
});
process.on("SIGTERM", () => {
  cleanup();
  process.exit(0);
});
process.on("SIGINT", () => {
  cleanup();
  process.exit(0);
});
server.listen(DAEMON_PORT, "127.0.0.1", () => {
  ensureWalletDir();
  nodeFs.writeFileSync(PID_FILE, String(process.pid), { mode: 384 });
  nodeFs.writeFileSync(PORT_FILE, String(DAEMON_PORT), { mode: 384 });
  log(`Daemon HTTP server on port ${DAEMON_PORT} (pid ${process.pid})`);
  connectingPromise = ensureConnected().then(() => {
    connectingPromise = null;
    log("SDK connected and ready");
  }).catch((err) => {
    connectingPromise = null;
    log(`SDK pre-warm failed: ${err.message} (will retry on first request)`);
  });
});
server.on("error", (err) => {
  if (err.code === "EADDRINUSE") {
    log(`Port ${DAEMON_PORT} in use. Is another daemon running?`);
    process.exit(1);
  }
  throw err;
});
