#!/usr/bin/env npx tsx

// teneo-skills-autogenerated/cli/index.ts
import "dotenv/config";
import { Command } from "commander";
import {
  createWalletClient,
  createPublicClient,
  http,
  defineChain
} from "viem";
import { privateKeyToAccount } from "viem/accounts";
import * as allChains from "viem/chains";
import * as nodeCrypto from "node:crypto";
import * as nodeFs from "node:fs";
import * as nodePath from "node:path";
import * as nodeOs from "node:os";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
var PRIVATE_KEY = process.env.TENEO_PRIVATE_KEY;
var DEFAULT_ROOM = process.env.TENEO_DEFAULT_ROOM || "";
var DEFAULT_CHAIN = process.env.TENEO_DEFAULT_CHAIN || "base";
var CHAIN_BY_ID = {};
for (const key of Object.keys(allChains)) {
  const c = allChains[key];
  if (c && typeof c === "object" && "id" in c)
    CHAIN_BY_ID[c.id] = c;
}
var WALLET_DIR = nodePath.join(nodeOs.homedir(), ".teneo-wallet");
var WALLET_FILE = nodePath.join(WALLET_DIR, "wallet.json");
var SECRET_FILE = nodePath.join(WALLET_DIR, ".secret");
function ensureWalletDir() {
  if (!nodeFs.existsSync(WALLET_DIR))
    nodeFs.mkdirSync(WALLET_DIR, { recursive: true, mode: 448 });
}
function getOrCreateMasterSecret() {
  ensureWalletDir();
  if (nodeFs.existsSync(SECRET_FILE)) {
    return Buffer.from(nodeFs.readFileSync(SECRET_FILE, "utf8").trim(), "hex");
  }
  const secret = nodeCrypto.randomBytes(32);
  nodeFs.writeFileSync(SECRET_FILE, secret.toString("hex"), { mode: 384 });
  nodeFs.chmodSync(SECRET_FILE, 384);
  return secret;
}
function encryptPK(pk, masterSecret) {
  const iv = nodeCrypto.randomBytes(12);
  const cipher = nodeCrypto.createCipheriv("aes-256-gcm", masterSecret, iv);
  const encrypted = Buffer.concat([cipher.update(pk, "utf8"), cipher.final()]);
  return {
    encryptedKey: encrypted.toString("base64"),
    iv: iv.toString("base64"),
    authTag: cipher.getAuthTag().toString("base64")
  };
}
function decryptPK(encryptedKey, iv, authTag, masterSecret) {
  const decipher = nodeCrypto.createDecipheriv("aes-256-gcm", masterSecret, Buffer.from(iv, "base64"));
  decipher.setAuthTag(Buffer.from(authTag, "base64"));
  return Buffer.concat([decipher.update(Buffer.from(encryptedKey, "base64")), decipher.final()]).toString("utf8");
}
function loadWallet() {
  if (!nodeFs.existsSync(WALLET_FILE)) return null;
  try {
    return JSON.parse(nodeFs.readFileSync(WALLET_FILE, "utf8"));
  } catch {
    return null;
  }
}
function saveWallet(data) {
  ensureWalletDir();
  nodeFs.writeFileSync(WALLET_FILE, JSON.stringify(data, null, 2), { mode: 384 });
  nodeFs.chmodSync(WALLET_FILE, 384);
}
function autoCreateWallet() {
  console.error(JSON.stringify({ info: "No wallet found \u2014 generating a new one automatically..." }));
  const privateKey = nodeCrypto.randomBytes(32).toString("hex");
  const account = privateKeyToAccount(`0x${privateKey}`);
  const secret = getOrCreateMasterSecret();
  const encrypted = encryptPK(privateKey, secret);
  saveWallet({
    address: account.address,
    encryptedKey: encrypted.encryptedKey,
    iv: encrypted.iv,
    authTag: encrypted.authTag,
    createdAt: (/* @__PURE__ */ new Date()).toISOString()
  });
  console.error(JSON.stringify({ info: `Wallet created: ${account.address}` }));
  console.error(JSON.stringify({ info: "Fund this address with USDC on Base, Avalanche, Peaq, or X Layer to use paid agents." }));
  return { address: account.address, privateKey };
}
function getWalletAddress() {
  const wallet = loadWallet();
  if (wallet) return wallet.address;
  if (PRIVATE_KEY) {
    const key = PRIVATE_KEY.startsWith("0x") ? PRIVATE_KEY : `0x${PRIVATE_KEY}`;
    return privateKeyToAccount(key).address;
  }
  return autoCreateWallet().address;
}
function requireKey() {
  if (PRIVATE_KEY) return PRIVATE_KEY;
  const wallet = loadWallet();
  if (wallet) {
    const secret = getOrCreateMasterSecret();
    return decryptPK(wallet.encryptedKey, wallet.iv, wallet.authTag, secret);
  }
  return autoCreateWallet().privateKey;
}
var USDC_ADDRESSES = {
  base: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
  avax: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E",
  peaq: "0xbbA60da06c2c5424f03f7434542280FCAd453d10",
  xlayer: "0x74b7F16337b8972027F6196A17a631aC6dE26d22"
};
var WALLET_CHAIN_MAP = {
  base: allChains.base,
  avax: allChains.avalanche,
  peaq: defineChain({
    id: 3338,
    name: "PEAQ",
    nativeCurrency: { name: "PEAQ", symbol: "PEAQ", decimals: 18 },
    rpcUrls: { default: { http: ["https://peaq.api.onfinality.io/public"] } }
  }),
  xlayer: defineChain({
    id: 196,
    name: "XLayer",
    nativeCurrency: { name: "OKB", symbol: "OKB", decimals: 18 },
    rpcUrls: { default: { http: ["https://rpc.xlayer.tech"] } }
  })
};
var ERC20_BALANCE_ABI = [{ inputs: [{ name: "account", type: "address" }], name: "balanceOf", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" }];
var ERC20_TRANSFER_ABI = [{ inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], name: "transfer", outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable", type: "function" }];
var JSON_FLAG = process.argv.includes("--json");
function out(data) {
  console.log(JSON.stringify(data, null, 2));
}
function fail(msg) {
  if (JSON_FLAG) console.error(JSON.stringify({ error: msg }));
  else console.error(`Error: ${msg}`);
  process.exit(1);
}
function normalizeDaemonError(error) {
  if (error.includes("Not connected to Teneo network")) {
    return "Connection to Teneo network was lost. The daemon is reconnecting \u2014 please retry in a few seconds.";
  }
  return error;
}
function parseTokenId(value, source = "--token-id") {
  if (value === void 0) return void 0;
  const tokenId = Number(value);
  if (!Number.isInteger(tokenId)) fail(`${source} must be a whole number`);
  return tokenId;
}
function pad(str, len) {
  return str.length >= len ? str.substring(0, len - 1) + " " : str + " ".repeat(len - str.length);
}
function padCenter(str, len) {
  if (str.length >= len) return str.substring(0, len);
  const left = Math.floor((len - str.length) / 2);
  return " ".repeat(left) + str + " ".repeat(len - str.length - left);
}
async function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}
var DAEMON_PID_FILE = nodePath.join(WALLET_DIR, "daemon.pid");
var DAEMON_PORT_FILE = nodePath.join(WALLET_DIR, "daemon.port");
function getDaemonPort() {
  try {
    return parseInt(nodeFs.readFileSync(DAEMON_PORT_FILE, "utf8").trim());
  } catch {
    return null;
  }
}
function isDaemonRunning() {
  try {
    const pid = parseInt(nodeFs.readFileSync(DAEMON_PID_FILE, "utf8").trim());
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}
async function startDaemonSafe() {
  console.error(JSON.stringify({ info: "Starting daemon..." }));
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = nodePath.dirname(__filename);
  const mjsPath = nodePath.join(__dirname, "daemon.mjs");
  const tsPath = nodePath.join(__dirname, "daemon.ts");
  const usePrecompiled = nodeFs.existsSync(mjsPath);
  const child = usePrecompiled ? spawn("node", [mjsPath], { detached: true, stdio: "ignore", cwd: __dirname, env: { ...process.env } }) : spawn("npx", ["tsx", tsPath], { detached: true, stdio: "ignore", cwd: __dirname, env: { ...process.env } });
  child.unref();
  for (let i = 0; i < 30; i++) {
    await sleep(500);
    const port = getDaemonPort();
    if (port) {
      try {
        const res = await fetch(`http://localhost:${port}/health`);
        if (res.ok) {
          console.error(JSON.stringify({ info: `Daemon ready on port ${port}` }));
          return { port };
        }
      } catch {
      }
    }
  }
  return { error: "Daemon failed to start within 15 seconds." };
}
async function startDaemon() {
  const result = await startDaemonSafe();
  if (result.error || !result.port) fail(result.error || "Daemon failed to start.");
  return result.port;
}
async function execViaDaemon(command, args = {}) {
  const response = await tryExecViaDaemon(command, args);
  if (response.error) fail(response.error);
  return response.result;
}
async function tryExecViaDaemon(command, args = {}) {
  let port = getDaemonPort();
  if (!port || !isDaemonRunning()) {
    const started = await startDaemonSafe();
    if (started.error || !started.port) return { error: started.error || "Daemon failed to start." };
    port = started.port;
  }
  let res;
  try {
    res = await fetch(`http://localhost:${port}/exec`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ command, args })
    });
  } catch (err) {
    console.error(JSON.stringify({ warn: "Daemon connection lost, restarting..." }));
    const restarted = await startDaemonSafe();
    if (restarted.error || !restarted.port) return { error: restarted.error || "Daemon failed to start." };
    port = restarted.port;
    res = await fetch(`http://localhost:${port}/exec`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ command, args })
    });
  }
  const data = await res.json();
  if (data.error) {
    return { error: normalizeDaemonError(data.error) };
  }
  return { result: data.result };
}
async function resolveRoom(opt) {
  if (opt) return opt;
  if (DEFAULT_ROOM) return DEFAULT_ROOM;
  const result = await execViaDaemon("rooms");
  if (result.rooms && result.rooms.length > 0) {
    const room = result.rooms[0];
    console.error(JSON.stringify({ info: `Using room: ${room.name || room.id}` }));
    return room.id;
  }
  console.error(JSON.stringify({ info: "No rooms found \u2014 creating one..." }));
  const created = await execViaDaemon("create-room", { name: "Default Room" });
  const roomId = created.room?.id;
  if (!roomId) fail("Failed to auto-create room.");
  console.error(JSON.stringify({ info: `Room created: ${roomId}` }));
  return roomId;
}
var program = new Command();
program.name("teneo-cli").version("2.0.34").description("Teneo Protocol CLI. Private keys are NEVER transmitted.").option("--json", "Machine-readable JSON output");
program.command("daemon").description("Manage the background daemon (start | stop | status)").argument("<action>", "start | stop | status").action(async (action) => {
  switch (action) {
    case "start": {
      if (isDaemonRunning()) {
        out({ status: "already_running", port: getDaemonPort() });
        return;
      }
      const port = await startDaemon();
      out({ status: "started", port });
      break;
    }
    case "stop": {
      const port = getDaemonPort();
      if (!port || !isDaemonRunning()) {
        out({ status: "not_running" });
        return;
      }
      try {
        await fetch(`http://localhost:${port}/stop`, { method: "POST" });
      } catch {
      }
      out({ status: "stopped" });
      break;
    }
    case "status": {
      const running = isDaemonRunning();
      out({ status: running ? "running" : "stopped", port: getDaemonPort() });
      break;
    }
    default:
      fail(`Unknown daemon action: ${action}. Use: start | stop | status`);
  }
});
program.command("health").description("Check connection health").action(async () => {
  console.error(`teneo-cli v${program.version()}`);
  out(await execViaDaemon("health"));
});
program.command("discover").description("Browse all network agents with commands and pricing (JSON)").action(async () => {
  out(await execViaDaemon("discover"));
});
program.command("list-agents").alias("agents").description("Browse agents on the Teneo network (use 'agent' commands to deploy your own)").option("--online", "Show only online agents").option("--free", "Show only agents with free commands").option("--search <keyword>", "Search by name/description").action(async (opts) => {
  const result = await execViaDaemon("list-agents", {
    online: opts.online,
    free: opts.free,
    search: opts.search
  });
  if (JSON_FLAG) {
    out(result);
    return;
  }
  const agents = result.agents || [];
  if (agents.length === 0) {
    console.log("No agents found.");
    return;
  }
  const col = { id: 28, name: 28, status: 8, cmds: 6, price: 14 };
  console.log("");
  console.log(pad("AGENT ID", col.id) + pad("NAME", col.name) + pad("STATUS", col.status) + pad("CMDS", col.cmds) + pad("PRICE RANGE", col.price));
  console.log("-".repeat(col.id + col.name + col.status + col.cmds + col.price));
  for (const agent of agents) {
    const prices = agent.commands.map((c) => c.price);
    const minP = Math.min(...prices.length ? prices : [0]);
    const maxP = Math.max(...prices.length ? prices : [0]);
    let priceRange = maxP === 0 ? "FREE" : minP === 0 ? `FREE-$${maxP}` : minP === maxP ? `$${minP}` : `$${minP}-$${maxP}`;
    console.log(pad(agent.agent_id, col.id) + pad(agent.agent_name, col.name) + (agent.is_online ? "ON    " : "OFF   ") + "  " + pad(String(agent.commands.length), col.cmds) + priceRange);
  }
  console.log(`
${agents.length} agent(s) found.`);
});
program.command("info").alias("agent-details").description("Show details, commands, and pricing for a network agent").argument("<agentId>").action(async (agentId) => {
  const result = await execViaDaemon("info", { agentId });
  if (result.error === "not_found") {
    if (JSON_FLAG) {
      out(result);
    } else {
      console.error(`Agent "${agentId}" not found.`);
      if (result.suggestions?.length) {
        console.log("\nDid you mean:");
        result.suggestions.forEach((s) => console.log(`  ${s}`));
      }
    }
    process.exit(1);
  }
  if (JSON_FLAG) {
    out(result);
    return;
  }
  const agent = result;
  console.log("\n" + "=".repeat(56));
  console.log(`  ${padCenter(agent.agent_name, 54)}`);
  console.log("=".repeat(56));
  console.log(`  ID:          ${agent.agent_id}`);
  console.log(`  Type:        ${agent.type}`);
  console.log(`  Status:      ${agent.is_online ? "ONLINE" : "OFFLINE"}`);
  if (agent.description) console.log(`  Description: ${agent.description}`);
  if (agent.commands?.length > 0) {
    console.log(`
  COMMANDS (${agent.commands.length}):`);
    console.log("  " + "-".repeat(60));
    for (const cmd of agent.commands) {
      const price = !cmd.price || cmd.price === 0 ? "FREE" : `$${cmd.price} USDC/${cmd.task_unit || "query"}`;
      console.log(`
  ${cmd.usage}`);
      if (cmd.description) console.log(`    ${cmd.description}`);
      console.log(`    Price: ${price}`);
      if (cmd.parameters?.length > 0) {
        console.log(`    Parameters:`);
        const maxName = Math.max(...cmd.parameters.map((p) => (p.name || "").length));
        const maxType = Math.max(...cmd.parameters.map((p) => (p.type || "string").length));
        for (const p of cmd.parameters) {
          const name = (p.name || "").padEnd(maxName);
          const type = (p.type || "string").padEnd(maxType);
          const req = p.required !== false ? "(required)" : "(optional)";
          const desc = p.description || "";
          console.log(`      ${name}  ${type}  ${req}  ${desc}`);
        }
      }
    }
  }
  console.log(`
  QUERY THIS AGENT:`);
  console.log(`    teneo-cli command ${agent.agent_id} "${agent.commands?.[0]?.trigger || "help"}" --room <roomId>
`);
});
program.command("command").description("Send a command to a network agent and get a response").argument("<agent>", "Internal agent ID (e.g. x-agent-enterprise-v2)").argument("<cmd>", "Command string: {trigger} {argument}").option("--room <roomId>").option("--timeout <ms>", "Response timeout", "120000").option("--chain <chain>", "Payment chain (base|avax|peaq|xlayer)").option("--network <network>", "Payment network (alias for --chain)").action(async (agent, cmd, opts) => {
  const room = await resolveRoom(opts.room);
  const chain = opts.chain || opts.network;
  out(await execViaDaemon("command", { agent, cmd, room, chain, timeout: parseInt(opts.timeout) }));
});
program.command("quote").description("Check price for a command (does not execute)").argument("<message>").option("--room <roomId>").option("--chain <chain>").action(async (message, opts) => {
  const room = await resolveRoom(opts.room);
  out(await execViaDaemon("quote", { message, room, chain: opts.chain || DEFAULT_CHAIN }));
});
program.command("rooms").description("List all rooms").action(async () => {
  out(await execViaDaemon("rooms"));
});
program.command("room-agents").description("List agents in room").argument("<roomId>").action(async (roomId) => {
  out(await execViaDaemon("room-agents", { roomId }));
});
program.command("create-room").description("Create room").argument("<name>").option("--description <desc>").option("--public", "Make room public", false).action(async (name, opts) => {
  out(await execViaDaemon("create-room", { name, description: opts.description, isPublic: opts.public }));
});
program.command("update-room").description("Update room").argument("<roomId>").option("--name <name>").option("--description <desc>").action(async (roomId, opts) => {
  out(await execViaDaemon("update-room", { roomId, name: opts.name, description: opts.description }));
});
program.command("delete-room").description("Delete room").argument("<roomId>").action(async (roomId) => {
  out(await execViaDaemon("delete-room", { roomId }));
});
program.command("add-agent").description("Add agent to room").argument("<roomId>").argument("<agentId>").action(async (roomId, agentId) => {
  out(await execViaDaemon("add-agent", { roomId, agentId }));
});
program.command("remove-agent").description("Remove agent from room").argument("<roomId>").argument("<agentId>").action(async (roomId, agentId) => {
  out(await execViaDaemon("remove-agent", { roomId, agentId }));
});
program.command("owned-rooms").description("List rooms you own").action(async () => {
  out(await execViaDaemon("owned-rooms"));
});
program.command("shared-rooms").description("List rooms shared with you").action(async () => {
  out(await execViaDaemon("shared-rooms"));
});
program.command("subscribe").description("Subscribe to public room").argument("<roomId>").action(async (roomId) => {
  out(await execViaDaemon("subscribe", { roomId }));
});
program.command("unsubscribe").description("Unsubscribe from room").argument("<roomId>").action(async (roomId) => {
  out(await execViaDaemon("unsubscribe", { roomId }));
});
program.command("room-available-agents").description("List agents available to add to a room").argument("<roomId>").action(async (roomId) => {
  out(await execViaDaemon("room-available-agents", { roomId }));
});
program.command("wallet-init").description("Show wallet status or create a new wallet").option("--force", "Force create a new wallet even if one exists").action(async (opts) => {
  if (!opts.force) {
    const existing = loadWallet();
    if (existing) {
      out({ status: "exists", address: existing.address, createdAt: existing.createdAt });
      return;
    }
    if (PRIVATE_KEY) {
      out({ status: "env_var_set", note: "Private key found in environment." });
      return;
    }
  }
  const { address } = autoCreateWallet();
  out({ status: "created", address, note: "New wallet generated. Fund with USDC to use paid agents." });
});
program.command("wallet-address").description("Show wallet public address").action(async () => {
  const wallet = loadWallet();
  if (wallet) {
    out({ address: wallet.address, createdAt: wallet.createdAt });
  } else if (PRIVATE_KEY) {
    const key = PRIVATE_KEY.startsWith("0x") ? PRIVATE_KEY : `0x${PRIVATE_KEY}`;
    out({ address: privateKeyToAccount(key).address, source: "environment_variable" });
  } else {
    const { address } = autoCreateWallet();
    out({ address, source: "auto_generated" });
  }
});
program.command("wallet-pubkey").description("Show wallet public key").action(async () => {
  const key = requireKey();
  const hex = key.startsWith("0x") ? key : `0x${key}`;
  const account = privateKeyToAccount(hex);
  out({ address: account.address, publicKey: account.publicKey });
});
program.command("wallet-export-key").description("Export private key (DANGEROUS)").action(async () => {
  const wallet = loadWallet();
  if (!wallet) fail(PRIVATE_KEY ? "No wallet file. Key is in environment." : "No wallet. Run wallet-init first.");
  const secret = getOrCreateMasterSecret();
  const key = decryptPK(wallet.encryptedKey, wallet.iv, wallet.authTag, secret);
  console.error(JSON.stringify({ warning: "PRIVATE KEY EXPORTED. Never share this." }));
  out({ address: wallet.address, privateKey: key });
});
program.command("wallet-balance").description("Check USDC and native token balances on supported chains").option("--chain <chain>", "Specific chain (base|avax|peaq|xlayer)").action(async (opts) => {
  const address = getWalletAddress();
  const chainsToCheck = opts.chain ? [opts.chain] : ["base", "avax", "peaq", "xlayer"];
  const results = {};
  for (const chainName of chainsToCheck) {
    const chain = WALLET_CHAIN_MAP[chainName];
    const usdcAddr = USDC_ADDRESSES[chainName];
    if (!chain || !usdcAddr) {
      results[chainName] = { error: `Unknown chain: ${chainName}` };
      continue;
    }
    try {
      const client = createPublicClient({ chain, transport: http() });
      const [usdcBalance, nativeBalance] = await Promise.all([
        client.readContract({
          address: usdcAddr,
          abi: ERC20_BALANCE_ABI,
          functionName: "balanceOf",
          args: [address]
        }),
        client.getBalance({ address })
      ]);
      const nativeSym = chain.nativeCurrency.symbol;
      const nativeDec = chain.nativeCurrency.decimals;
      results[chainName] = {
        usdc: (Number(usdcBalance) / 1e6).toFixed(6),
        usdc_raw: usdcBalance.toString(),
        [nativeSym.toLowerCase()]: (Number(nativeBalance) / 10 ** nativeDec).toFixed(8),
        [`${nativeSym.toLowerCase()}_raw`]: nativeBalance.toString()
      };
    } catch (err) {
      results[chainName] = { error: err.message };
    }
  }
  out({ address, balances: results });
});
program.command("wallet-send").description("Send USDC to any address").argument("<amount>", "Amount in USDC").argument("<to>", "Destination address").argument("<chain>", "Chain (base|avax|peaq|xlayer)").action(async (amountStr, to, chainName) => {
  const amount = parseFloat(amountStr);
  if (isNaN(amount) || amount <= 0) fail("Invalid amount.");
  if (!to.startsWith("0x") || to.length !== 42) fail("Invalid address. Must be 0x + 40 hex chars.");
  const rawAmount = BigInt(Math.round(amount * 1e6));
  const chain = WALLET_CHAIN_MAP[chainName];
  const usdcAddr = USDC_ADDRESSES[chainName];
  if (!chain || !usdcAddr) fail(`Unknown chain: ${chainName}. Supported: base, avax, peaq, xlayer`);
  const key = requireKey();
  const account = privateKeyToAccount(key.startsWith("0x") ? key : `0x${key}`);
  const wc = createWalletClient({ account, chain, transport: http() });
  const txHash = await wc.writeContract({
    address: usdcAddr,
    abi: ERC20_TRANSFER_ABI,
    functionName: "transfer",
    args: [to, rawAmount]
  });
  out({ status: "sent", txHash, amount: amountStr, chain: chainName, to });
});
program.command("check-balance").description("Check USDC balances across all payment networks (via daemon)").option("--chain <chain>", "Check specific chain only").action(async (opts) => {
  out(await execViaDaemon("check-balance", { chain: opts.chain }));
});
program.command("export-login").description("Print export TENEO_PRIVATE_KEY=... for shell reuse").action(async () => {
  const key = requireKey();
  console.log(`export TENEO_PRIVATE_KEY=${key}`);
});
var BACKEND_REST_URL = process.env.TENEO_BACKEND_URL || "https://backend.developer.chatroom.teneo-protocol.ai";
var VALID_CATEGORIES = [
  "Trading",
  "Finance",
  "Crypto",
  "Social Media",
  "Lead Generation",
  "E-Commerce",
  "SEO",
  "News",
  "Real Estate",
  "Travel",
  "Automation",
  "Developer Tools",
  "AI",
  "Integrations",
  "Open Source",
  "Jobs",
  "Price Lists",
  "Other"
];
var VALID_AGENT_TYPES = ["command", "nlp", "commandless", "mcp"];
var VALID_PRICE_TYPES = ["task-transaction"];
var VALID_TASK_UNITS = ["per-query", "per-item"];
var VALID_PARAM_TYPES = ["string", "number", "username", "boolean", "url", "id", "interval", "datetime", "enum"];
function validateAgentId(agentId) {
  if (!agentId) return "agentId is required";
  if (!/^[a-z0-9][a-z0-9-]*[a-z0-9]$/.test(agentId) && !/^[a-z0-9]$/.test(agentId))
    return "agentId must use lowercase letters, numbers, hyphens only, and start/end with a letter or number";
  return null;
}
function validateMetadata(meta) {
  const errors = [];
  if (!meta.name) errors.push({ field: "name", message: "name is required" });
  const agentId = meta.agent_id || meta.agentId;
  if (!agentId) errors.push({ field: "agent_id", message: "agent_id is required" });
  else {
    const idErr = validateAgentId(agentId);
    if (idErr) errors.push({ field: "agent_id", message: idErr });
  }
  const shortDesc = meta.short_description || meta.shortDescription;
  if (!shortDesc) errors.push({ field: "short_description", message: "short_description is required" });
  if (!meta.description) errors.push({ field: "description", message: "description is required" });
  const agentType = meta.agent_type || meta.agentType;
  if (!agentType) errors.push({ field: "agent_type", message: "agent_type is required" });
  else if (!VALID_AGENT_TYPES.includes(agentType))
    errors.push({ field: "agent_type", message: `agent_type must be one of: ${VALID_AGENT_TYPES.join(", ")}` });
  if (!meta.capabilities || !Array.isArray(meta.capabilities))
    errors.push({ field: "capabilities", message: "capabilities array is required" });
  if (!meta.categories || !Array.isArray(meta.categories) || meta.categories.length === 0)
    errors.push({ field: "categories", message: "at least one category is required" });
  else {
    for (const cat of meta.categories) {
      if (!VALID_CATEGORIES.includes(cat))
        errors.push({ field: "categories", message: `invalid category "${cat}". Valid: ${VALID_CATEGORIES.join(", ")}` });
    }
  }
  if (meta.commands && Array.isArray(meta.commands)) {
    for (let i = 0; i < meta.commands.length; i++) {
      const cmd = meta.commands[i];
      if (!cmd.trigger) errors.push({ field: `commands[${i}].trigger`, message: "trigger is required" });
      if (!cmd.description) errors.push({ field: `commands[${i}].description`, message: "description is required" });
      if (cmd.pricePerUnit !== void 0 && (typeof cmd.pricePerUnit !== "number" || cmd.pricePerUnit < 0))
        errors.push({ field: `commands[${i}].pricePerUnit`, message: "pricePerUnit must be a non-negative number" });
      if (cmd.priceType && !VALID_PRICE_TYPES.includes(cmd.priceType))
        errors.push({ field: `commands[${i}].priceType`, message: `priceType must be one of: ${VALID_PRICE_TYPES.join(", ")}` });
      if (cmd.taskUnit && !VALID_TASK_UNITS.includes(cmd.taskUnit))
        errors.push({ field: `commands[${i}].taskUnit`, message: `taskUnit must be one of: ${VALID_TASK_UNITS.join(", ")}` });
      if (cmd.parameters && Array.isArray(cmd.parameters)) {
        for (let j = 0; j < cmd.parameters.length; j++) {
          const p = cmd.parameters[j];
          if (!p.name) errors.push({ field: `commands[${i}].parameters[${j}].name`, message: "parameter name is required" });
          if (p.type && !VALID_PARAM_TYPES.includes(p.type))
            errors.push({ field: `commands[${i}].parameters[${j}].type`, message: `type must be one of: ${VALID_PARAM_TYPES.join(", ")}` });
          if (p.type === "enum" && (!p.options || !Array.isArray(p.options) || p.options.length === 0))
            errors.push({ field: `commands[${i}].parameters[${j}].options`, message: "enum type requires non-empty options array" });
        }
      }
    }
  }
  return errors;
}
function toKebabCase(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}
var agentCmd = program.command("agent").description("Deploy your own agents on the Teneo network");
agentCmd.addHelpCommand(false);
var agentHelpText = `Usage: teneo agent <command>

Deploy your own agents on the Teneo network.

Workflow:
  init <name>              Create a new agent project (scaffolds Go code + metadata)
  deploy <directory>       Build, mint NFT, and start as background service
  publish <agentId>        Make your agent public (free, reviewed within 72h)

Management:
  status <agentId>         Show agent status (network + local service)
  logs <agentId>           Tail agent logs
  list                     List all your agents
  services                 List locally running agent services
  undeploy <agentId>       Stop and remove background service
  unpublish <agentId>      Remove from public listing

Utilities:
  validate <file>          Validate a metadata JSON file
`;
agentCmd.helpInformation = () => `${agentHelpText}
`;
var TOKEN_REGISTRY_FILE = nodePath.join(WALLET_DIR, "agent-tokens.json");
function loadTokenRegistry() {
  try {
    if (nodeFs.existsSync(TOKEN_REGISTRY_FILE)) {
      return JSON.parse(nodeFs.readFileSync(TOKEN_REGISTRY_FILE, "utf8"));
    }
  } catch {
  }
  return {};
}
function saveTokenToRegistry(agentId, tokenId) {
  ensureWalletDir();
  const reg = loadTokenRegistry();
  reg[agentId] = { token_id: tokenId };
  nodeFs.writeFileSync(TOKEN_REGISTRY_FILE, JSON.stringify(reg, null, 2));
}
function removeTokenFromRegistry(agentId) {
  const reg = loadTokenRegistry();
  if (reg[agentId]) {
    delete reg[agentId];
    nodeFs.writeFileSync(TOKEN_REGISTRY_FILE, JSON.stringify(reg, null, 2));
  }
}
async function waitForTokenId(agentId, timeoutMs = 3e4) {
  const logFile = nodePath.join(AGENT_LOG_DIR, `${agentId}.err.log`);
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    try {
      if (nodeFs.existsSync(logFile)) {
        const content = nodeFs.readFileSync(logFile, "utf8");
        const match = content.match(/token_id=(\d+)/);
        if (match) return parseInt(match[1]);
      }
    } catch {
    }
    await new Promise((r) => setTimeout(r, 1e3));
  }
  return null;
}
async function resolveTokenId(agentId, manualTokenId, action = "publish") {
  if (manualTokenId !== void 0) return manualTokenId;
  const reg = loadTokenRegistry();
  if (reg[agentId]?.token_id) return reg[agentId].token_id;
  const daemonResult = await tryExecViaDaemon("my-agent-status", { agentId, walletAddress: getWalletAddress() });
  if (daemonResult.result?.token_id) {
    saveTokenToRegistry(agentId, daemonResult.result.token_id);
    return daemonResult.result.token_id;
  }
  const logFile = nodePath.join(AGENT_LOG_DIR, `${agentId}.err.log`);
  try {
    if (nodeFs.existsSync(logFile)) {
      const content = nodeFs.readFileSync(logFile, "utf8");
      const match = content.match(/token_id=(\d+)/);
      if (match) {
        const tokenId = parseInt(match[1]);
        saveTokenToRegistry(agentId, tokenId);
        return tokenId;
      }
    }
  } catch {
  }
  fail(`Cannot ${action} \u2014 no token ID found. Deploy the agent first: teneo agent deploy ./${agentId}`);
}
var GO_VERSION = "1.24.1";
var GO_LOCAL_DIR = nodePath.join(WALLET_DIR, "go");
async function ensureGo() {
  const { execSync } = await import("node:child_process");
  const localGoBin = nodePath.join(GO_LOCAL_DIR, "bin");
  if (nodeFs.existsSync(localGoBin) && !process.env.PATH?.includes(localGoBin)) {
    process.env.PATH = `${localGoBin}:${process.env.PATH}`;
  }
  try {
    const gopath = execSync("go env GOPATH", { encoding: "utf8", stdio: "pipe", timeout: 5e3 }).trim();
    if (gopath && !process.env.PATH?.includes(nodePath.join(gopath, "bin"))) {
      process.env.PATH = `${nodePath.join(gopath, "bin")}:${process.env.PATH}`;
    }
  } catch {
  }
  try {
    const version = execSync("go version", { encoding: "utf8", stdio: "pipe", timeout: 5e3 }).trim();
    console.error(JSON.stringify({ info: version }));
    return;
  } catch {
  }
  console.error(JSON.stringify({ info: "Go not found \u2014 installing automatically (no sudo required)..." }));
  const platform2 = nodeOs.platform();
  const arch2 = nodeOs.arch();
  const goArch = arch2 === "arm64" ? "arm64" : "amd64";
  let tarUrl;
  if (platform2 === "darwin") {
    tarUrl = `https://go.dev/dl/go${GO_VERSION}.darwin-${goArch}.tar.gz`;
  } else if (platform2 === "linux") {
    tarUrl = `https://go.dev/dl/go${GO_VERSION}.linux-${goArch}.tar.gz`;
  } else {
    fail(`Cannot auto-install Go on ${platform2}. Install Go ${GO_VERSION}+ manually from https://go.dev/dl/`);
    return;
  }
  try {
    ensureWalletDir();
    const tarPath = nodePath.join(WALLET_DIR, "go.tar.gz");
    console.error(JSON.stringify({ info: `Downloading Go ${GO_VERSION}...` }));
    execSync(`curl -fsSL "${tarUrl}" -o "${tarPath}"`, { stdio: "pipe", timeout: 12e4 });
    if (nodeFs.existsSync(GO_LOCAL_DIR)) {
      execSync(`rm -rf "${GO_LOCAL_DIR}"`, { stdio: "pipe" });
    }
    execSync(`tar -C "${WALLET_DIR}" -xzf "${tarPath}"`, { stdio: "pipe", timeout: 6e4 });
    nodeFs.unlinkSync(tarPath);
    process.env.PATH = `${localGoBin}:${process.env.PATH}`;
    if (!process.env.GOPATH) {
      process.env.GOPATH = nodePath.join(nodeOs.homedir(), "go");
    }
    const version = execSync("go version", { encoding: "utf8", stdio: "pipe", timeout: 5e3 }).trim();
    console.error(JSON.stringify({ info: `Installed: ${version} (at ${GO_LOCAL_DIR})` }));
  } catch (err) {
    fail(`Failed to install Go: ${err.message}. Install manually from https://go.dev/dl/`);
  }
}
var SDK_FALLBACK_VERSION = "v0.8.0";
async function getLatestSDKVersion() {
  try {
    const res = await fetch("https://api.github.com/repos/TeneoProtocolAI/teneo-agent-sdk/tags?per_page=1", {
      headers: { "Accept": "application/vnd.github+json" },
      signal: AbortSignal.timeout(5e3)
    });
    if (res.ok) {
      const tags = await res.json();
      if (tags.length > 0 && tags[0].name) {
        console.error(JSON.stringify({ info: `Using Teneo Agent SDK ${tags[0].name} (latest)` }));
        return tags[0].name;
      }
    }
  } catch {
  }
  console.error(JSON.stringify({ info: `Using Teneo Agent SDK ${SDK_FALLBACK_VERSION} (fallback)` }));
  return SDK_FALLBACK_VERSION;
}
async function scaffoldAgent(meta, opts) {
  await ensureGo();
  const agentId = meta.agent_id || meta.agentId;
  const dir = agentId;
  if (nodeFs.existsSync(dir)) fail(`Directory "${dir}" already exists.`);
  nodeFs.mkdirSync(dir, { recursive: true });
  let agentKey;
  if (opts.useCliKey) {
    agentKey = requireKey();
    console.error(JSON.stringify({ info: "Using CLI wallet key for agent." }));
  } else {
    agentKey = nodeCrypto.randomBytes(32).toString("hex");
    console.error(JSON.stringify({ info: "Generated new private key for agent." }));
  }
  const sdkVersion = await getLatestSDKVersion();
  const metaFilename = `${agentId}-metadata.json`;
  nodeFs.writeFileSync(nodePath.join(dir, metaFilename), JSON.stringify(meta, null, 2));
  nodeFs.writeFileSync(nodePath.join(dir, ".env"), `PRIVATE_KEY=${agentKey}
ACCEPT_EULA=true
`, { mode: 384 });
  nodeFs.writeFileSync(nodePath.join(dir, "go.mod"), `module ${agentId}

go 1.24

require (
	github.com/TeneoProtocolAI/teneo-agent-sdk ${sdkVersion}
	github.com/joho/godotenv v1.5.1
)
`);
  let mainGo;
  if (opts.type === "simple-openai") {
    mainGo = `package main

import (
	"context"
	"log"
	"os"

	"github.com/TeneoProtocolAI/teneo-agent-sdk/pkg/agent"
	"github.com/joho/godotenv"
)

func main() {
	_ = godotenv.Load()
	ctx := context.Background()

	a := agent.NewSimpleOpenAIAgent(agent.SimpleOpenAIAgentConfig{
		PrivateKey: os.Getenv("PRIVATE_KEY"),
		OpenAIKey:  os.Getenv("OPENAI_API_KEY"),
	})
	if err := a.Run(ctx); err != nil {
		log.Fatal(err)
	}
}
`;
  } else {
    const cases = (meta.commands || []).map((cmd) => {
      if (cmd.trigger === "help") {
        const triggers = (meta.commands || []).map((c) => c.trigger).join(", ");
        return `	case "help":
		return "available commands: ${triggers}", nil`;
      }
      return `	case "${cmd.trigger}":
		return fmt.Sprintf("${cmd.trigger} called with args: %v", args), nil`;
    });
    if (!meta.commands?.some((c) => c.trigger === "help")) {
      const triggers = (meta.commands || []).map((c) => c.trigger).join(", ");
      cases.push(`	case "help":
		return "available commands: ${triggers}", nil`);
    }
    mainGo = `package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/TeneoProtocolAI/teneo-agent-sdk/pkg/agent"
	"github.com/TeneoProtocolAI/teneo-agent-sdk/pkg/nft"
	"github.com/joho/godotenv"
)

type MyAgent struct{}

func (a *MyAgent) ProcessTask(ctx context.Context, task string) (string, error) {
	parts := strings.Fields(task)
	if len(parts) == 0 {
		return "no command provided \u2014 try 'help'", nil
	}
	command := parts[0]
	args := parts[1:]

	switch command {
${cases.join("\n")}
	default:
		return fmt.Sprintf("unknown command: %s (args: %v)", command, args), nil
	}
}

func main() {
	_ = godotenv.Load()

	result, err := nft.Mint("${metaFilename}")
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Agent ready \u2014 token_id=%d", result.TokenID)

	raw, _ := os.ReadFile("${metaFilename}")
	var meta struct {
		Name        string \`json:"name"\`
		AgentID     string \`json:"agent_id"\`
		Description string \`json:"description"\`
	}
	json.Unmarshal(raw, &meta)

	cfg := agent.DefaultConfig()
	cfg.AgentID = meta.AgentID
	cfg.Name = meta.Name
	cfg.Description = meta.Description
	cfg.PrivateKey = os.Getenv("PRIVATE_KEY")

	a, err := agent.NewEnhancedAgent(&agent.EnhancedAgentConfig{
		Config:       cfg,
		AgentHandler: &MyAgent{},
		TokenID:      result.TokenID,
	})
	if err != nil {
		log.Fatal(err)
	}

	if err := a.Run(); err != nil {
		log.Fatal(err)
	}
}
`;
  }
  nodeFs.writeFileSync(nodePath.join(dir, "main.go"), mainGo);
  nodeFs.writeFileSync(nodePath.join(dir, ".gitignore"), `.env
${agentId}
`);
  try {
    const { execSync } = await import("node:child_process");
    execSync("go mod tidy", { cwd: dir, stdio: "pipe", timeout: 3e4 });
    console.error(JSON.stringify({ info: "go mod tidy completed successfully." }));
  } catch {
    console.error(JSON.stringify({ warn: "go mod tidy failed \u2014 run it manually after installing Go 1.24+." }));
  }
  return { dir, agentId, files: [metaFilename, "main.go", "go.mod", ".env", ".gitignore"] };
}
agentCmd.command("init").description("Create a new agent project (scaffolds Go code + metadata)").argument("<name>", "Agent name").option("--id <id>", "Agent ID (kebab-case, derived from name if omitted)").option("--type <type>", "Agent type (command|nlp|commandless|mcp)").option("--template <template>", "Go template: enhanced (default) or simple-openai", "enhanced").option("--description <desc>", "Agent description").option("--short-description <desc>", "Short description").option("--category <cat>", "Category (can specify multiple)", (val, prev) => prev.concat(val), []).option("--metadata-only", "Only create metadata JSON, skip Go project scaffolding").option("--use-cli-key", "Reuse the CLI wallet key for the agent").action(async (name, opts) => {
  let agentId = opts.id;
  let agentType = opts.type || "command";
  let description = opts.description;
  let shortDescription = opts.shortDescription;
  let categories = opts.category?.length ? opts.category : [];
  const missing = [];
  if (!description) missing.push("--description");
  if (!shortDescription) missing.push("--short-description");
  if (categories.length === 0) missing.push("--category");
  if (missing.length > 0) {
    const msg = `Missing required fields: ${missing.join(", ")}

Example:
  teneo agent init "My Agent" --type command \\
    --description "Full description of what the agent does" \\
    --short-description "One-line summary" \\
    --category "AI"`;
    if (JSON_FLAG) {
      out({ error: msg });
    } else {
      console.error(`Error: ${msg}`);
    }
    process.exit(1);
  }
  if (!agentId) agentId = toKebabCase(name);
  const metadata = {
    name,
    agent_id: agentId,
    short_description: shortDescription,
    description,
    agent_type: agentType,
    capabilities: [],
    commands: agentType === "command" ? [
      {
        trigger: "help",
        description: "Lists all commands and usage examples.",
        parameters: [],
        strictArg: true,
        minArgs: 0,
        maxArgs: 0,
        pricePerUnit: 0,
        priceType: "task-transaction",
        taskUnit: "per-query"
      }
    ] : [],
    nlp_fallback: agentType !== "command",
    categories,
    metadata_version: "2.4.0"
  };
  const errors = validateMetadata(metadata);
  if (errors.length > 0) {
    if (JSON_FLAG) {
      out({ status: "error", errors });
    } else {
      console.error("Validation errors:");
      errors.forEach((e) => console.error(`  ${e.field}: ${e.message}`));
    }
    process.exit(1);
  }
  const metadataOnly = opts.metadataOnly;
  if (!metadataOnly) {
    const result = await scaffoldAgent(metadata, { type: opts.template || "enhanced", useCliKey: !!opts.useCliKey });
    const metaFile = `${result.dir}/${agentId}-metadata.json`;
    if (JSON_FLAG) {
      out({
        status: "created",
        agent_id: agentId,
        name,
        directory: result.dir,
        files: result.files,
        next_steps: [
          `Edit ${metaFile} to define your commands and pricing`,
          `Edit ${result.dir}/main.go to implement your agent logic in ProcessTask`,
          `teneo agent deploy ./${result.dir}`,
          `teneo agent publish ${agentId}`
        ]
      });
    } else {
      console.log(`
Created agent: ${agentId}
`);
      console.log(`  Files:`);
      console.log(`    ${metaFile}   <- commands, pricing, description`);
      console.log(`    ${result.dir}/main.go${" ".repeat(Math.max(0, metaFile.length - `${result.dir}/main.go`.length))}   <- your agent logic (ProcessTask)`);
      console.log(`    ${result.dir}/.env${" ".repeat(Math.max(0, metaFile.length - `${result.dir}/.env`.length))}   <- private key (auto-generated)`);
      console.log(``);
      console.log(`  What to do now:`);
      console.log(`  1. Edit ${metaFile}`);
      console.log(`     - Add your commands to the "commands" array (trigger, description, price)`);
      console.log(`     - Update the description and short_description`);
      console.log(``);
      console.log(`  2. Edit ${result.dir}/main.go`);
      console.log(`     - Implement your logic in the ProcessTask function`);
      console.log(`     - The switch/case maps command triggers to your code`);
      console.log(``);
      console.log(`  3. When ready, deploy:`);
      console.log(`     teneo agent deploy ./${result.dir}`);
      console.log(``);
      console.log(`  Everything is free. Minting costs nothing. No gas fees.`);
      console.log(``);
    }
  } else {
    const filename = `${agentId}-metadata.json`;
    nodeFs.writeFileSync(filename, JSON.stringify(metadata, null, 2));
    if (JSON_FLAG) {
      out({
        status: "created",
        file: filename,
        agent_id: agentId,
        name,
        next_steps: [
          `Edit ${filename} to add commands, pricing, description, and short_description`,
          `Run teneo agent init "${name}" --id ${agentId} --type ${agentType} --description "${description}" --short-description "${shortDescription}" --category "${categories[0]}" to scaffold the Go project later`
        ]
      });
    } else {
      console.log(`
Created agent metadata: ${filename}
`);
      console.log(`  What to do now:`);
      console.log(`  1. Edit ${filename}`);
      console.log(`     - Add your commands to the "commands" array (trigger, description, price)`);
      console.log(`     - Update the description and short_description`);
      console.log(``);
      console.log(`  2. When ready to scaffold the Go project:`);
      console.log(`     teneo agent init "${name}" --id ${agentId} --type ${agentType} --description "${description}" --short-description "${shortDescription}" --category "${categories[0]}"`);
      console.log(``);
    }
  }
});
agentCmd.command("validate").description("Validate agent metadata JSON file").argument("<file>", "Path to metadata JSON file").action(async (file) => {
  if (!nodeFs.existsSync(file)) fail(`File not found: ${file}`);
  let meta;
  try {
    meta = JSON.parse(nodeFs.readFileSync(file, "utf8"));
  } catch {
    fail(`Invalid JSON in ${file}`);
  }
  const errors = validateMetadata(meta);
  if (errors.length > 0) {
    if (JSON_FLAG) {
      out({ status: "invalid", errors });
    } else {
      console.error(`Validation failed (${errors.length} error${errors.length > 1 ? "s" : ""}):`);
      errors.forEach((e) => console.error(`  ${e.field}: ${e.message}`));
    }
    process.exit(1);
  }
  out({ status: "valid", agent_id: meta.agent_id || meta.agentId, name: meta.name, commands: meta.commands?.length || 0, categories: meta.categories });
});
async function publishAgent(agentId, manualTokenId) {
  const tokenId = await resolveTokenId(agentId, manualTokenId, "publish");
  const key = requireKey();
  const hex = key.startsWith("0x") ? key : `0x${key}`;
  const address = privateKeyToAccount(hex).address;
  const res = await fetch(`${BACKEND_REST_URL}/api/agents/${agentId}/submit-for-review`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ creator_wallet: address, token_id: tokenId })
  });
  const data = await res.json();
  if (!res.ok) fail(data.message || data.error || `HTTP ${res.status}`);
  if (JSON_FLAG) {
    out({ status: "published", agentId, tokenId, ...data });
  } else {
    console.log(`
Published: ${agentId}
`);
    console.log(`  Status:  pending review (typically approved within 72h)`);
    console.log(`  Your agent will appear in the public Agent Console after review.
`);
    console.log(`  To check status:    teneo agent status ${agentId}`);
    console.log(`  To unpublish:       teneo agent unpublish ${agentId}`);
    console.log(``);
  }
}
async function unpublishAgent(agentId, manualTokenId) {
  const tokenId = await resolveTokenId(agentId, manualTokenId, "unpublish");
  const key = requireKey();
  const hex = key.startsWith("0x") ? key : `0x${key}`;
  const address = privateKeyToAccount(hex).address;
  const res = await fetch(`${BACKEND_REST_URL}/api/agents/${agentId}/withdraw-public`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ creator_wallet: address, token_id: tokenId })
  });
  const data = await res.json();
  if (!res.ok) fail(data.message || data.error || `HTTP ${res.status}`);
  if (JSON_FLAG) out({ status: "unpublished", agentId, tokenId, ...data });
  else console.log(`
Unpublished: ${agentId}
`);
}
agentCmd.command("publish").description("Make your agent public (free, reviewed within 72h)").argument("<agentId>", "Agent ID").option("--token-id <id>", "NFT token ID (auto-detected if omitted)").action(async (agentId, opts) => {
  await publishAgent(agentId, parseTokenId(opts.tokenId));
});
agentCmd.command("unpublish").description("Remove your agent from public listing").argument("<agentId>", "Agent ID").option("--token-id <id>", "NFT token ID (auto-detected if omitted)").action(async (agentId, opts) => {
  await unpublishAgent(agentId, parseTokenId(opts.tokenId));
});
agentCmd.command("list").description("List agents owned by this wallet").action(async () => {
  const result = await execViaDaemon("my-agents", { walletAddress: getWalletAddress() });
  if (JSON_FLAG) {
    out(result);
    return;
  }
  const agents = result.agents || [];
  if (agents.length === 0) {
    console.log("No agents found for this wallet.");
    return;
  }
  const col = { id: 28, name: 28, status: 10, token: 8 };
  console.log("");
  console.log(pad("AGENT ID", col.id) + pad("NAME", col.name) + pad("STATUS", col.status) + pad("TOKEN", col.token));
  console.log("-".repeat(col.id + col.name + col.status + col.token));
  for (const agent of agents) {
    console.log(
      pad(agent.agent_id, col.id) + pad(agent.agent_name, col.name) + pad(agent.is_online ? "ONLINE" : "OFFLINE", col.status) + pad(String(agent.token_id || "-"), col.token)
    );
  }
  console.log(`
${agents.length} agent(s) owned by this wallet.`);
});
async function getNetworkStatus(agentId) {
  const response = await tryExecViaDaemon("my-agent-status", { agentId, walletAddress: getWalletAddress() });
  if (response.error) return { data: null, error: response.error };
  return { data: response.result, error: null };
}
async function showAgentStatus(agentId) {
  const networkStatus = await getNetworkStatus(agentId);
  const service = await getLocalServiceStatus(agentId);
  const daemonUnavailable = !!networkStatus.error;
  if (!networkStatus.data && service.status === "not_installed") {
    fail(`Agent '${agentId}' not found. List your agents: teneo agent list`);
  }
  if (JSON_FLAG) {
    out({
      agent_id: agentId,
      ...networkStatus.data ? {
        name: networkStatus.data.agent_name || agentId,
        is_online: networkStatus.data.is_online,
        visibility: networkStatus.data.visibility,
        token_id: networkStatus.data.token_id
      } : {},
      ...daemonUnavailable ? { note: "Network status unavailable; showing local service info only." } : {},
      service
    });
    return;
  }
  console.log(``);
  console.log(`  Agent:        ${networkStatus.data?.agent_name || agentId}`);
  if (networkStatus.data) {
    console.log(`  Network:      ${networkStatus.data.is_online ? "ONLINE" : "OFFLINE"}`);
    console.log(`  Visibility:   ${networkStatus.data.visibility || "unknown"}`);
    if (networkStatus.data.token_id) console.log(`  Token ID:     ${networkStatus.data.token_id}`);
  } else {
    console.log(`  Network:      unavailable (showing local service info only)`);
  }
  console.log(``);
  if (service.status !== "not_installed") {
    console.log(`  Service:      ${service.status}${service.pid ? ` (PID ${service.pid})` : ""}`);
    console.log(`  Platform:     ${service.platform}`);
    if (service.logs?.stderr) console.log(`  Logs:         ${service.logs.stderr}`);
  } else {
    console.log(`  Service:      not installed locally`);
  }
  console.log(``);
}
agentCmd.command("status").description("Show agent status (network + local service)").argument("<agentId>", "Agent ID").action(async (agentId) => {
  await showAgentStatus(agentId);
});
agentCmd.command("logs").description("Tail agent logs").argument("<agentId>", "Agent ID").option("--lines <n>", "Number of lines to show", "50").option("--no-follow", "Don't follow (just print and exit)").action(async (agentId, opts) => {
  const logFile = nodePath.join(AGENT_LOG_DIR, `${agentId}.err.log`);
  if (!nodeFs.existsSync(logFile)) {
    fail(`No logs found for "${agentId}". Deploy first: teneo agent deploy ./${agentId}`);
  }
  const { spawn: spawnProc } = await import("node:child_process");
  const args = ["-n", opts.lines];
  if (opts.follow !== false) args.push("-f");
  const tail = spawnProc("tail", [...args, logFile], { stdio: "inherit" });
  tail.on("close", (code) => process.exit(code ?? 0));
});
var AGENT_LOG_DIR = nodePath.join(WALLET_DIR, "logs");
var SERVICE_LABEL_PREFIX = "ai.teneo.agent";
function getServiceLabel(agentId) {
  return `${SERVICE_LABEL_PREFIX}.${agentId}`;
}
function getMacPlistPath(agentId) {
  return nodePath.join(nodeOs.homedir(), "Library", "LaunchAgents", `${getServiceLabel(agentId)}.plist`);
}
function getLinuxUnitPath(agentId) {
  return nodePath.join(nodeOs.homedir(), ".config", "systemd", "user", `${agentId}.service`);
}
function generateMacPlist(agentId, binaryPath, workDir) {
  const logDir = AGENT_LOG_DIR;
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${getServiceLabel(agentId)}</string>
    <key>Program</key>
    <string>${binaryPath}</string>
    <key>WorkingDirectory</key>
    <string>${workDir}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${logDir}/${agentId}.out.log</string>
    <key>StandardErrorPath</key>
    <string>${logDir}/${agentId}.err.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin</string>
    </dict>
</dict>
</plist>
`;
}
function generateLinuxUnit(agentId, binaryPath, workDir) {
  const logs = getAgentLogPaths(agentId);
  return `[Unit]
Description=Teneo Agent: ${agentId}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${binaryPath}
WorkingDirectory=${workDir}
Restart=always
RestartSec=5
Environment=PATH=/usr/local/bin:/usr/bin:/bin
StandardOutput=append:${logs.stdout}
StandardError=append:${logs.stderr}

[Install]
WantedBy=default.target
`;
}
function getAgentLogPaths(agentId) {
  return {
    stdout: `${AGENT_LOG_DIR}/${agentId}.out.log`,
    stderr: `${AGENT_LOG_DIR}/${agentId}.err.log`
  };
}
async function getLocalServiceStatus(agentId) {
  const { execSync } = await import("node:child_process");
  const platform2 = nodeOs.platform();
  const logs = getAgentLogPaths(agentId);
  if (platform2 === "darwin") {
    const plistPath = getMacPlistPath(agentId);
    if (!nodeFs.existsSync(plistPath)) return { status: "not_installed" };
    try {
      const result = execSync(`launchctl list ${getServiceLabel(agentId)} 2>&1`, { encoding: "utf8", stdio: "pipe" });
      const pidMatch = result.match(/"PID"\s*=\s*(\d+)/);
      return {
        status: pidMatch ? "running" : "stopped",
        pid: pidMatch ? parseInt(pidMatch[1]) : null,
        platform: "macOS",
        plist: plistPath,
        logs
      };
    } catch {
      return { status: "stopped", platform: "macOS", plist: plistPath, logs };
    }
  }
  if (platform2 === "linux") {
    const unitPath = getLinuxUnitPath(agentId);
    if (!nodeFs.existsSync(unitPath)) return { status: "not_installed" };
    try {
      const result = execSync(`systemctl --user is-active ${agentId} 2>&1`, { encoding: "utf8", stdio: "pipe" }).trim();
      const pidResult = execSync(`systemctl --user show ${agentId} --property=MainPID --value 2>&1`, { encoding: "utf8", stdio: "pipe" }).trim();
      return {
        status: result === "active" ? "running" : result,
        pid: parseInt(pidResult) || null,
        platform: "Linux",
        unit: unitPath,
        logs
      };
    } catch {
      return { status: "stopped", platform: "Linux", unit: unitPath, logs };
    }
  }
  fail(`Unsupported platform: ${platform2}`);
}
function findMetadataInDir(dir) {
  const files = nodeFs.readdirSync(dir).filter((f) => f.endsWith("-metadata.json"));
  if (files.length === 0) fail(`No *-metadata.json file found in ${dir}`);
  if (files.length > 1) fail(`Multiple metadata files found in ${dir}: ${files.join(", ")}. Expected exactly one.`);
  const raw = nodeFs.readFileSync(nodePath.join(dir, files[0]), "utf8");
  return JSON.parse(raw);
}
async function deployAgent(directory) {
  const { execSync } = await import("node:child_process");
  const platform2 = nodeOs.platform();
  if (platform2 !== "darwin" && platform2 !== "linux") fail(`Unsupported platform: ${platform2}. Only macOS and Linux are supported.`);
  const absDir = nodePath.resolve(directory);
  if (!nodeFs.existsSync(absDir)) fail(`Directory not found: ${directory}. Create an agent first: teneo agent init ${nodePath.basename(directory)}`);
  const meta = findMetadataInDir(absDir);
  const agentId = meta.agent_id || meta.agentId;
  if (!agentId) fail("agent_id not found in metadata JSON.");
  let binaryPath = nodePath.join(absDir, agentId);
  if (!nodeFs.existsSync(binaryPath)) {
    await ensureGo();
    console.error(JSON.stringify({ info: `Building ${agentId}...` }));
    try {
      execSync(`go build -o ${agentId} .`, { cwd: absDir, stdio: "pipe", timeout: 12e4 });
      console.error(JSON.stringify({ info: "Build successful." }));
    } catch (err) {
      fail(`go build failed: ${err.stderr?.toString() || err.message}`);
    }
  }
  if (!nodeFs.existsSync(binaryPath)) fail(`Binary not found at ${binaryPath} after build.`);
  if (!nodeFs.existsSync(AGENT_LOG_DIR)) {
    nodeFs.mkdirSync(AGENT_LOG_DIR, { recursive: true, mode: 448 });
  }
  if (platform2 === "darwin") {
    const plistPath = getMacPlistPath(agentId);
    const plistDir = nodePath.dirname(plistPath);
    if (!nodeFs.existsSync(plistDir)) nodeFs.mkdirSync(plistDir, { recursive: true });
    try {
      execSync(`launchctl unload "${plistPath}" 2>/dev/null`, { stdio: "pipe" });
    } catch {
    }
    nodeFs.writeFileSync(plistPath, generateMacPlist(agentId, binaryPath, absDir));
    execSync(`launchctl load "${plistPath}"`, { stdio: "pipe" });
  } else {
    const unitPath = getLinuxUnitPath(agentId);
    const unitDir = nodePath.dirname(unitPath);
    if (!nodeFs.existsSync(unitDir)) nodeFs.mkdirSync(unitDir, { recursive: true });
    nodeFs.writeFileSync(unitPath, generateLinuxUnit(agentId, binaryPath, absDir));
    try {
      execSync("loginctl enable-linger $USER", { stdio: "pipe" });
    } catch {
    }
    execSync("systemctl --user daemon-reload", { stdio: "pipe" });
    execSync(`systemctl --user enable --now ${agentId}`, { stdio: "pipe" });
  }
  console.error(JSON.stringify({ info: "Service started. Waiting for NFT mint..." }));
  const tokenId = await waitForTokenId(agentId, 3e4);
  if (tokenId) saveTokenToRegistry(agentId, tokenId);
  const service = await getLocalServiceStatus(agentId);
  const logs = getAgentLogPaths(agentId);
  const nextSteps = [
    `teneo agent publish ${agentId}`,
    `teneo agent status ${agentId}`,
    `teneo agent logs ${agentId}`
  ];
  if (JSON_FLAG) {
    out({
      status: "deployed",
      agentId,
      tokenId: tokenId || null,
      service,
      logs,
      ...tokenId ? {} : { warning: `NFT minting in progress \u2014 check status later: teneo agent status ${agentId}` },
      next_steps: nextSteps
    });
    return;
  }
  console.log(`
Deployed: ${agentId}
`);
  if (tokenId) {
    console.log(`  NFT minted:  token #${tokenId} (free, gasless)`);
  } else {
    console.log(`  NFT minting: in progress \u2014 check status later: teneo agent status ${agentId}`);
  }
  console.log(`  Service:     ${service.status}${service.pid ? ` (PID ${service.pid})` : ""}`);
  console.log(`  Logs:        ${logs.stderr}`);
  console.log(``);
  console.log(`  Your agent is live on the Teneo network.`);
  console.log(`  Only you can see it right now (private).`);
  console.log(``);
  console.log(`  To make it public:  teneo agent publish ${agentId}`);
  console.log(`  To check status:    teneo agent status ${agentId}`);
  console.log(`  To view logs:       teneo agent logs ${agentId}`);
  console.log(``);
}
agentCmd.command("deploy").description("Build, mint NFT, and start as background service").argument("<directory>", "Path to the agent project directory").action(async (directory) => {
  await deployAgent(directory);
});
async function undeployAgent(agentId) {
  const { execSync } = await import("node:child_process");
  const platform2 = nodeOs.platform();
  if (platform2 === "darwin") {
    const plistPath = getMacPlistPath(agentId);
    if (!nodeFs.existsSync(plistPath)) fail(`Service not found for "${agentId}". List services: teneo agent services`);
    try {
      execSync(`launchctl unload "${plistPath}"`, { stdio: "pipe" });
    } catch {
    }
    nodeFs.unlinkSync(plistPath);
  } else if (platform2 === "linux") {
    const unitPath = getLinuxUnitPath(agentId);
    if (!nodeFs.existsSync(unitPath)) fail(`Service not found for "${agentId}". List services: teneo agent services`);
    try {
      execSync(`systemctl --user disable --now ${agentId}`, { stdio: "pipe" });
    } catch {
    }
    nodeFs.unlinkSync(unitPath);
    try {
      execSync("systemctl --user daemon-reload", { stdio: "pipe" });
    } catch {
    }
  } else {
    fail(`Unsupported platform: ${platform2}`);
  }
  removeTokenFromRegistry(agentId);
  out({ status: "undeployed", agentId, platform: platform2 === "darwin" ? "macOS" : "Linux" });
}
agentCmd.command("undeploy").description("Stop and remove background service").argument("<agentId>", "Agent ID").action(async (agentId) => {
  await undeployAgent(agentId);
});
agentCmd.command("services").description("List all locally installed agent services").action(async (opts) => {
  const { execSync } = await import("node:child_process");
  const platform2 = nodeOs.platform();
  const agents = [];
  if (platform2 === "darwin") {
    const launchDir = nodePath.join(nodeOs.homedir(), "Library", "LaunchAgents");
    if (nodeFs.existsSync(launchDir)) {
      const plists = nodeFs.readdirSync(launchDir).filter((f) => f.startsWith(`${SERVICE_LABEL_PREFIX}.`) && f.endsWith(".plist"));
      for (const plist of plists) {
        const agentId = plist.replace(`${SERVICE_LABEL_PREFIX}.`, "").replace(".plist", "");
        const label = getServiceLabel(agentId);
        let status = "stopped";
        let pid = null;
        try {
          const result = execSync(`launchctl list ${label} 2>&1`, { encoding: "utf8", stdio: "pipe" });
          const pidMatch = result.match(/"PID"\s*=\s*(\d+)/);
          if (pidMatch) {
            pid = parseInt(pidMatch[1]);
            status = "running";
          }
        } catch {
        }
        agents.push({ agentId, status, pid, plist: nodePath.join(launchDir, plist) });
      }
    }
  } else if (platform2 === "linux") {
    const unitDir = nodePath.join(nodeOs.homedir(), ".config", "systemd", "user");
    if (nodeFs.existsSync(unitDir)) {
      const units = nodeFs.readdirSync(unitDir).filter((f) => f.endsWith(".service"));
      for (const unit of units) {
        const agentId = unit.replace(".service", "");
        let status = "stopped";
        let pid = null;
        try {
          const result = execSync(`systemctl --user is-active ${agentId} 2>&1`, { encoding: "utf8", stdio: "pipe" }).trim();
          status = result === "active" ? "running" : result;
          if (status === "running") {
            const pidResult = execSync(`systemctl --user show ${agentId} --property=MainPID --value 2>&1`, { encoding: "utf8", stdio: "pipe" }).trim();
            pid = parseInt(pidResult) || null;
          }
        } catch {
        }
        agents.push({ agentId, status, pid, unit: nodePath.join(unitDir, unit) });
      }
    }
  } else {
    fail(`Unsupported platform: ${platform2}`);
  }
  if (JSON_FLAG) {
    out({ count: agents.length, agents, platform: platform2 === "darwin" ? "macOS" : "Linux" });
    return;
  }
  if (agents.length === 0) {
    console.log("No agent services installed.");
    return;
  }
  const col = { id: 30, status: 10, pid: 8 };
  console.log("");
  console.log(pad("AGENT ID", col.id) + pad("STATUS", col.status) + pad("PID", col.pid));
  console.log("-".repeat(col.id + col.status + col.pid));
  for (const a of agents) {
    console.log(pad(a.agentId, col.id) + pad(a.status.toUpperCase(), col.status) + pad(a.pid ? String(a.pid) : "-", col.pid));
  }
  console.log(`
${agents.length} service(s) installed.`);
});
program.command("update").description("Update the Teneo CLI to the latest version").action(async () => {
  const { execSync } = await import("node:child_process");
  console.log("Updating Teneo CLI...");
  try {
    try {
      execSync("kill $(cat ~/.teneo-daemon.pid 2>/dev/null) 2>/dev/null", { stdio: "ignore" });
    } catch {
    }
    execSync("npx -y @teneo-protocol/cli", { stdio: "inherit" });
  } catch (err) {
    console.error("Update failed:", err.message || err);
    process.exit(1);
  }
});
program.command("version").description("Show installed and latest available version").action(async () => {
  const local = program.version();
  console.log(`Installed: v${local}`);
  try {
    const { execSync } = await import("node:child_process");
    const latest = execSync("npm view @teneo-protocol/cli version", { encoding: "utf-8", timeout: 1e4 }).trim();
    console.log(`Latest:    v${latest}`);
    if (local !== latest) {
      console.log(`
Update available! Run: ~/teneo-skill/teneo update`);
    } else {
      console.log(`
You're up to date.`);
    }
  } catch {
    console.log("Latest:    (could not check)");
  }
});
if (process.argv.includes("--dump-commands")) {
  let dumpCommand = function(cmd) {
    const entry = {
      name: cmd.name(),
      description: cmd.description(),
      arguments: cmd.registeredArguments.map((a) => ({ name: a.name(), description: a.description, required: a.required })),
      options: cmd.options.map((o) => ({ flags: o.flags, description: o.description, defaultValue: o.defaultValue }))
    };
    const subs = cmd.commands;
    if (subs && subs.length > 0) {
      entry.subcommands = subs.map(dumpCommand);
    }
    return entry;
  };
  dumpCommand2 = dumpCommand;
  const commands = program.commands.map(dumpCommand);
  console.log(JSON.stringify({ name: program.name(), version: program.version(), description: program.description(), commands }, null, 2));
  process.exit(0);
}
var dumpCommand2;
program.parseAsync(process.argv).then(() => {
  setTimeout(() => process.exit(0), 100).unref();
}).catch((err) => fail(err.message || String(err)));
